"""Pydantic request/response schemas."""
from datetime import datetime
from typing import Any

from pydantic import BaseModel, EmailStr, Field, computed_field, field_validator


# ── Auth ──────────────────────────────────────────────────────────────────────

class LoginRequest(BaseModel):
    username: str = Field(min_length=1, max_length=64)
    password: str = Field(min_length=1)
    totp_code: str | None = Field(default=None, pattern=r"^\d{6}$")


class TokenResponse(BaseModel):
    access_token: str
    refresh_token: str
    token_type: str = "bearer"
    mfa_required: bool = False


class RefreshRequest(BaseModel):
    refresh_token: str


class MFASetupResponse(BaseModel):
    secret: str
    provisioning_uri: str


class MFAVerifyRequest(BaseModel):
    totp_code: str = Field(pattern=r"^\d{6}$")


# ── Users ─────────────────────────────────────────────────────────────────────

def _validate_password_strength(value: str) -> str:
    if not any(c.isupper() for c in value):
        raise ValueError("Password must contain at least one uppercase letter")
    if not any(c.islower() for c in value):
        raise ValueError("Password must contain at least one lowercase letter")
    if not any(c.isdigit() for c in value):
        raise ValueError("Password must contain at least one digit")
    if not any(c in "!@#$%^&*()-_=+[]{}|;:,.<>?" for c in value):
        raise ValueError("Password must contain at least one special character")
    return value


class UserCreate(BaseModel):
    username: str = Field(min_length=3, max_length=64)
    email: EmailStr
    password: str = Field(min_length=12)
    role: str = Field(default="viewer")

    @field_validator("role")
    @classmethod
    def validate_role(cls, v: str) -> str:
        valid = {"system_admin", "security_officer", "assessor", "reviewer", "system_owner", "viewer"}
        if v not in valid:
            raise ValueError(f"role must be one of {valid}")
        return v

    @field_validator("password")
    @classmethod
    def validate_password(cls, v: str) -> str:
        return _validate_password_strength(v)


class UserUpdate(BaseModel):
    email: EmailStr | None = None
    role: str | None = None
    is_active: bool | None = None


class UserPasswordReset(BaseModel):
    password: str = Field(min_length=12)

    @field_validator("password")
    @classmethod
    def validate_password(cls, v: str) -> str:
        return _validate_password_strength(v)


class UserResponse(BaseModel):
    id: int
    username: str
    email: str
    role: str
    mfa_enabled: bool
    is_active: bool
    created_at: datetime
    last_login: datetime | None

    model_config = {"from_attributes": True}


# ── Projects ──────────────────────────────────────────────────────────────────

class ProjectCreate(BaseModel):
    name: str = Field(min_length=1, max_length=255)
    description: str | None = None
    system_type: str | None = None
    impact_baseline: str = Field(default="moderate")

    @field_validator("impact_baseline")
    @classmethod
    def validate_baseline(cls, v: str) -> str:
        if v not in {"low", "moderate", "high"}:
            raise ValueError("impact_baseline must be low, moderate, or high")
        return v


class ProjectUpdate(BaseModel):
    name: str | None = None
    description: str | None = None
    system_type: str | None = None
    impact_baseline: str | None = None


class ProjectResponse(BaseModel):
    id: int
    name: str
    description: str | None
    system_type: str | None
    impact_baseline: str
    owner_id: int
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


# ── Documents ─────────────────────────────────────────────────────────────────

class DocumentResponse(BaseModel):
    id: int
    project_id: int
    filename: str
    file_type: str
    file_hash: str
    file_size_bytes: int
    parse_status: str
    parse_error: str | None = None
    page_count: int | None
    created_at: datetime
    tag_count: int | None = None
    autogenerated: bool = False
    source_assessment_id: int | None = None
    source_assessment_run_number: int | None = None
    source_remediation_report_id: int | None = None

    model_config = {"from_attributes": True}


# ── Assessments ───────────────────────────────────────────────────────────────

class AssessmentStartRequest(BaseModel):
    llm_provider: str = Field(default="ollama")
    llm_model: str | None = None
    context_strategy: str = Field(default="rag")
    ollama_num_ctx: int | None = Field(default=None, ge=2048, le=262144)
    skip_stage3: bool = Field(default=False)
    carry_forward_compliant: bool = Field(
        default=True,
        description="Carry forward compliant findings from the most recent assessment instead of re-testing them.",
    )

    @field_validator("llm_provider")
    @classmethod
    def validate_provider(cls, v: str) -> str:
        if v not in {"ollama", "claude", "bedrock"}:
            raise ValueError("llm_provider must be ollama, claude, or bedrock")
        return v

    @field_validator("context_strategy")
    @classmethod
    def validate_strategy(cls, v: str) -> str:
        if v not in {"rag", "full", "hybrid"}:
            raise ValueError("context_strategy must be rag, full, or hybrid")
        return v


class AssessmentResponse(BaseModel):
    id: int
    project_id: int
    project_run_number: int = 1
    policy_id: int | None = None
    policy_version: int | None = None
    name: str | None = None
    notes: str | None = None
    status: str
    llm_provider: str
    llm_model: str
    context_strategy: str
    controls_total: int
    controls_complete: int
    error_message: str | None
    started_at: datetime | None
    completed_at: datetime | None
    paused_at: datetime | None = None
    progress_detail: str | None = None
    skip_stage3: bool = False
    carry_forward_compliant: bool = True

    @property
    def run_duration_seconds(self) -> int | None:
        if self.started_at and self.completed_at:
            return int((self.completed_at - self.started_at).total_seconds())
        return None

    model_config = {"from_attributes": True}


class AssessmentUpdateRequest(BaseModel):
    name: str | None = Field(default=None, max_length=200)
    notes: str | None = None


# ── Control Findings ──────────────────────────────────────────────────────────

class FindingReviewRequest(BaseModel):
    reviewer_status: str
    reviewer_note: str | None = None

    @field_validator("reviewer_status")
    @classmethod
    def validate_reviewer_status(cls, v: str) -> str:
        if v not in {"accepted", "override", "revision_requested"}:
            raise ValueError("reviewer_status must be accepted, override, or revision_requested")
        return v


class ControlFindingResponse(BaseModel):
    id: int
    assessment_id: int
    control_id: str
    control_family: str
    control_title: str
    status: str
    implementation_statement: str | None
    gaps: list | None
    evidence_citations: list | None
    remediation_plan: str | None
    confidence_score: float | None
    rule_signal: str | None
    raw_llm_response: str | None = None
    needs_manual_review: bool = False
    retry_count: int = 0
    notes: str | None = None
    tested_at: datetime | None = None
    reviewer_status: str | None
    reviewer_note: str | None
    reviewed_at: datetime | None
    carried_forward: bool = False
    applicability_changed: bool = False
    prev_status: str | None = None
    override_applied: str | None = None
    # Option C: LLM dissent note (if stage-2.5 reviewer challenged the code verdict)
    llm_challenge_note: str | None = None
    # Issue 5: True when implementation_statement was auto-synthesized (skip_stage3 or LLM failure)
    synthesized_narrative: bool = False

    # Option D: NIST 800-53A formal determination — computed from status at serialization.
    # Internal DB keeps compliant/partially_compliant/non_compliant for working views;
    # formal reports use Satisfied / Other Than Satisfied per NIST 800-53A.
    @computed_field
    @property
    def nist_determination(self) -> dict:
        from app.services.multistage_engine import nist_determination
        return nist_determination(self.status)

    model_config = {"from_attributes": True}


class FindingNotesRequest(BaseModel):
    notes: str | None = None


class FindingManualResolveRequest(BaseModel):
    status: str
    implementation_statement: str
    gaps: list[str] = []
    remediation_plan: str | None = None
    confidence_score: float = Field(default=0.5, ge=0.0, le=1.0)
    reviewer_note: str | None = None

    @field_validator("status")
    @classmethod
    def validate_status(cls, v: str) -> str:
        valid = {"compliant", "partially_compliant", "non_compliant", "not_applicable"}
        if v not in valid:
            raise ValueError(f"status must be one of {valid}")
        return v


# ── Control Overrides ─────────────────────────────────────────────────────────

class ControlOverrideRequest(BaseModel):
    applicability: str | None = Field(default=None)  # "applicable"|"not_applicable"|"inherited"|None
    applicability_rationale: str | None = None
    satisfied: bool | None = None
    satisfied_rationale: str | None = None
    risk_accepted: bool | None = None
    risk_acceptance_rationale: str | None = None
    risk_acceptance_expiry: datetime | None = None
    # Manual status override — protected from automated re-assessment
    manual_status: str | None = Field(default=None)
    manual_status_rationale: str | None = None
    clear_manual_status: bool = False  # set True to remove the override

    @field_validator("applicability")
    @classmethod
    def validate_applicability(cls, v):
        if v is not None and v not in {"applicable", "not_applicable", "inherited"}:
            raise ValueError("applicability must be applicable, not_applicable, inherited, or null")
        return v

    @field_validator("manual_status")
    @classmethod
    def validate_manual_status(cls, v):
        valid = {"compliant", "partially_compliant", "non_compliant", "not_applicable"}
        if v is not None and v not in valid:
            raise ValueError(f"manual_status must be one of {valid}")
        return v


class ControlOverrideResponse(BaseModel):
    id: int
    project_id: int
    control_id: str
    applicability: str | None
    applicability_rationale: str | None
    applicability_set_by: str | None
    applicability_set_at: datetime | None
    satisfied: bool
    satisfied_rationale: str | None
    satisfied_set_by: str | None
    satisfied_set_at: datetime | None
    risk_accepted: bool
    risk_acceptance_rationale: str | None
    risk_accepted_by: str | None
    risk_accepted_at: datetime | None
    risk_acceptance_expiry: datetime | None
    manual_status: str | None
    manual_status_rationale: str | None
    manual_status_set_by: str | None
    manual_status_set_at: datetime | None
    updated_at: datetime

    model_config = {"from_attributes": True}


# ── Control Activity Log ──────────────────────────────────────────────────────

class ControlActivityLogResponse(BaseModel):
    id: int
    project_id: int
    assessment_id: int | None
    control_id: str
    control_family: str
    control_title: str
    action_type: str
    action_summary: str
    details: Any | None
    performed_by: str
    performed_at: datetime

    model_config = {"from_attributes": True}


# ── POAM ──────────────────────────────────────────────────────────────────────

class POAMCreate(BaseModel):
    control_id: str
    finding: str
    risk_level: str
    weakness: str | None = None
    remediation_plan: str | None = None
    due_date: datetime | None = None
    owner_id: int | None = None

    @field_validator("risk_level")
    @classmethod
    def validate_risk(cls, v: str) -> str:
        if v not in {"critical", "high", "medium", "low"}:
            raise ValueError("risk_level must be critical, high, medium, or low")
        return v


class POAMResponse(BaseModel):
    id: int
    poam_id: str
    control_id: str
    finding: str
    risk_level: str
    status: str
    due_date: datetime | None
    created_at: datetime

    model_config = {"from_attributes": True}


# ── Security Events ───────────────────────────────────────────────────────────

class SecurityEventResponse(BaseModel):
    id: int
    timestamp: datetime
    event_type: str
    severity: str
    description: str
    user_id: int | None
    source_ip: str | None
    resolved: bool

    model_config = {"from_attributes": True}


# ── Scorecard ─────────────────────────────────────────────────────────────────

class ScorecardSummary(BaseModel):
    total_controls: int
    implemented: int
    partially_implemented: int
    not_implemented: int
    inherited: int
    not_applicable: int
    compliance_score: float  # 0.0 - 100.0
    open_poams: int
    critical_events_unresolved: int
