"""Staged assessment pipeline built on top of evidence units from ingestion."""
from __future__ import annotations

import asyncio
import hashlib
import json
import re
from collections import defaultdict
from typing import Any

from sqlalchemy import delete, func, or_, select
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import get_settings
from app.models.orm import (
    AssessmentChallenge,
    AssessmentCriteriaPackage,
    AssessmentEvidenceTriage,
    ControlDetermination,
    Document,
    EvidenceClassification,
    EvidenceUnit,
    IngestionRun,
    ObjectiveDetermination,
    ObjectiveEvidenceReview,
    ProjectCommonProvider,
)
from app.services.assessment_policy import DEFAULT_THRESHOLDS, resolve_bucket_context
from app.services.closure_guidance import build_objective_closure_guidance, evaluate_contract_coverage
from app.services.evidence_profiles import normalize_autogenerated_profile
from app.services.llm.base import LLMFinding
from app.services.multistage_engine import (
    _derive_objectives_from_statement,
    _synthesize_narrative,
    run_gap_analysis,
    run_narrative,
    run_verdict_challenge,
)

settings = get_settings()


def evidence_scope_fingerprint(entries: list[dict[str, Any]]) -> str | None:
    """Hash the exact evidence files and ingestion runs approved for an assessment."""
    if not entries:
        return None
    normalized = sorted(entries, key=lambda item: int(item["document_id"]))
    return hashlib.sha256(
        json.dumps(normalized, sort_keys=True, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


def is_legacy_unverified_ingestion(fallback_stages: Any) -> bool:
    """Recognize only the transition marker applied to pre-governance ingestion runs."""
    return set(fallback_stages or []) == {"legacy_fallback_detected"}


def is_assessment_ready_ingestion(run: IngestionRun) -> bool:
    """Return whether an ingestion run may enter a new frozen assessment scope."""
    return (
        run.status == "complete"
        and run.quality_status == "passed"
        and run.readiness_eligible
        and not is_legacy_unverified_ingestion(run.fallback_stages)
    )


def _unready_project_documents(document_runs: list[tuple[Any, Any | None]]) -> list[dict[str, Any]]:
    """Describe project evidence that cannot yet be frozen into an assessment scope."""
    indexed_statuses = {"complete", "indexed"}
    unready: list[dict[str, Any]] = []
    for document, run in document_runs:
        if document.parse_status in indexed_statuses and run is not None and run.status == "complete":
            continue
        unready.append(
            {
                "document_id": document.id,
                "filename": document.filename,
                "parse_status": document.parse_status,
                "run_id": run.id if run is not None else None,
                "run_status": run.status if run is not None else None,
                "error_stage": run.error_stage if run is not None else None,
                "error_message": run.error_message if run is not None else document.parse_error,
            }
        )
    return unready


def _resolve_objective_review_concurrency(llm) -> int:
    configured = max(2, min(8, int(settings.assessment_concurrency)))
    model = str(getattr(llm, "model", "") or "").strip().lower()
    provider_hint = type(llm).__name__.lower()

    if "ollama" in provider_hint:
        if "120b" in model or "405b" in model:
            return min(configured, 2)
        if "70b" in model or "72b" in model or "cloud" in model:
            return min(configured, 3)
        return min(configured, 4)

    if "claude" in provider_hint or "bedrock" in provider_hint:
        return min(configured, 4)

    return configured

_STRENGTH_WEIGHT = {
    "strong": 1.0,
    "moderate": 0.8,
    "weak": 0.45,
    "insufficient": 0.1,
}

_SOURCE_WEIGHT = {
    "project": 0.16,
    "common_control": 0.16,
    "policy": 0.1,
    "procedure": 0.1,
}

_ARTIFACT_BONUS = {
    "technical_config": 0.15,
    "implementation_statement": 0.12,
    "test_evidence": 0.1,
    "procedure": 0.08,
    "policy": 0.04,
    "audit_artifact": -0.05,
    "other": 0.0,
}

_EVIDENCE_STRENGTH_SCORE = {
    "strong": 1.0,
    "moderate": 0.78,
    "weak": 0.50,
    "insufficient": 0.20,
}

_ARTIFACT_QUALITY_SCORE = {
    "technical_config": 0.16,
    "implementation_statement": 0.10,
    "test_evidence": 0.14,
    "procedure": 0.08,
    "policy": 0.04,
    "audit_artifact": -0.10,
    "other": 0.0,
}


def _objective_status_label(status: str | None) -> str:
    return {
        "met": "Met",
        "partially_met": "Partially met",
        "partial": "Partially met",
        "not_met": "Not met",
    }.get(str(status or "").strip(), "Needs review")


def _human_gap_detail(row: dict) -> str:
    missing_evidence = str(row.get("missing_evidence") or "").strip()
    if missing_evidence:
        return missing_evidence
    rationale = str(row.get("rationale") or "").strip()
    if rationale and not re.search(r"Bucket=|effective_support=|evidence_quality=|critical=true|weight=", rationale):
        return rationale
    objective_text = str(row.get("objective_text") or "").strip()
    if objective_text:
        return f"Evidence does not fully demonstrate: {objective_text}"
    return "Evidence does not fully demonstrate this objective."


def _build_gaps_from_objective_rows(objective_rows: list[dict], status: str) -> list[str]:
    gaps: list[str] = []
    for row in objective_rows or []:
        if str(row.get("status") or "") == "met":
            continue
        objective_id = str(row.get("objective_id") or "objective").strip()
        detail = _human_gap_detail(row)
        gaps.append(f"{objective_id} ({_objective_status_label(row.get('status'))}): {detail}")
    return gaps

_SOURCE_QUALITY_SCORE = {
    "project": 0.08,
    "common_control": 0.08,
    "policy": 0.02,
    "procedure": 0.03,
}


def _source_type_for_doc(doc: Document, project_id: int) -> str:
    if doc.project_id == project_id:
        return "project"
    if doc.provider_id is not None:
        return "common_control"
    if doc.policy_library_id is not None:
        return "policy"
    if doc.procedure_library_id is not None:
        return "procedure"
    return "project"


def _triage_role(cls: EvidenceClassification | None, doc: Document) -> str:
    if doc.document_intent in {"documents_gaps", "evaluates"} and doc.document_type in {"audit_finding", "assessment_report", "other"}:
        return "contradictory"
    if doc.document_intent == "plans":
        return "partial"
    if cls and cls.evidence_strength == "insufficient":
        return "irrelevant"
    if cls and cls.evidence_strength == "weak":
        return "partial"
    return "supporting"


def _extract_objective_text(objective: str) -> tuple[str, str]:
    if ":" in objective:
        obj_id, text = objective.split(":", 1)
        return obj_id.strip(), text.strip()
    return objective.strip(), objective.strip()


def _normalize_objective_id(objective_id: str | None) -> str:
    value = str(objective_id or "").strip()
    leading_label = re.match(
        r"^\s*([A-Za-z]{2,3}-\d{1,2}(?:\(\d+\))?(?:[a-z])?(?:\.\d+)?\.?(?:\[[^\]]+\])?)(?=\s|:|-|$)",
        value,
    )
    if leading_label:
        return leading_label.group(1).strip()[:128]
    if ":" in value:
        value = value.split(":", 1)[0].strip()
    return value[:128]


def _objective_alias_key(objective_id: str | None) -> str:
    value = _normalize_objective_id(objective_id).upper()
    tokens = re.findall(r"[A-Z]+|\d+", value)
    normalized_tokens = [
        (token.lstrip("0") or "0") if token.isdigit() else token
        for token in tokens
    ]
    return "".join(normalized_tokens)


def _build_objective_id_aliases(objectives: list[str]) -> dict[str, str]:
    aliases: dict[str, str] = {}
    for objective in objectives:
        obj_id, objective_text = _extract_objective_text(objective)
        canonical_id = _normalize_objective_id(obj_id)
        if not canonical_id:
            continue
        candidates = {
            obj_id,
            canonical_id,
            objective,
            f"{obj_id}: {objective_text}" if objective_text else obj_id,
        }
        for candidate in candidates:
            key = _objective_alias_key(candidate)
            if key:
                aliases.setdefault(key, canonical_id)
    return aliases


def _canonical_objective_id(objective_id: str | None, aliases: dict[str, str]) -> str:
    normalized = _normalize_objective_id(objective_id)
    if not normalized:
        return ""
    key = _objective_alias_key(objective_id)
    if key and key in aliases:
        return aliases[key]
    normalized_key = _objective_alias_key(normalized)
    if normalized_key and normalized_key in aliases:
        return aliases[normalized_key]
    return normalized


def _packet_id(control_id: str, objective_id: str, packet: dict[str, Any]) -> str:
    """Stable objective-specific ID used to bind LLM citations to evidence packets."""
    control_part = re.sub(r"[^A-Za-z0-9]+", "-", control_id or "control").strip("-").upper()
    objective_part = re.sub(r"[^A-Za-z0-9]+", "-", objective_id or "objective").strip("-").upper()
    unit = packet.get("unit_id")
    doc = packet.get("document_id")
    if unit is not None or doc is not None:
        basis = f"d{doc or 'x'}-u{unit or 'x'}"
    else:
        raw = "|".join([
            str(packet.get("filename") or ""),
            str(packet.get("section_path") or ""),
            str(packet.get("content") or "")[:240],
        ])
        basis = hashlib.sha1(raw.encode("utf-8", errors="ignore")).hexdigest()[:12]
    return f"PKT-{control_part}-{objective_part}-{basis}"[:128]


def _dedupe_objectives(objectives: list[str]) -> list[str]:
    deduped: list[str] = []
    seen: set[str] = set()
    for objective in objectives:
        obj_id, _ = _extract_objective_text(objective)
        key = _normalize_objective_id(obj_id)
        if not key or key in seen:
            continue
        seen.add(key)
        deduped.append(objective)
    return deduped


def _objective_priority(result: dict[str, Any]) -> tuple[int, int, int]:
    met_rank = {
        "yes": 3,
        "partial": 2,
        "no": 1,
    }.get(result.get("met"), 0)
    has_quote = 1 if result.get("evidence_quote") else 0
    has_gap = 1 if result.get("gap") else 0
    return (met_rank, has_quote, has_gap)


def _dedupe_gap_analysis(gap_analysis: list[dict[str, Any]], objectives: list[str]) -> list[dict[str, Any]]:
    aliases = _build_objective_id_aliases(objectives)
    expected_order = []
    for objective in objectives:
        obj_id, _ = _extract_objective_text(objective)
        norm = _normalize_objective_id(obj_id)
        if norm:
            expected_order.append(norm)

    best_by_id: dict[str, dict[str, Any]] = {}
    extras: list[str] = []
    for item in gap_analysis:
        raw_obj_id = str(item.get("objective_id") or "").strip()
        obj_id = _canonical_objective_id(raw_obj_id, aliases)
        if not obj_id:
            continue
        normalized = {
            **item,
            "objective_id": obj_id,
        }
        if raw_obj_id and raw_obj_id != obj_id:
            normalized.setdefault("raw_objective_id", raw_obj_id)
        current = best_by_id.get(obj_id)
        if current is None or _objective_priority(normalized) > _objective_priority(current):
            best_by_id[obj_id] = normalized
        if obj_id not in expected_order and obj_id not in extras:
            extras.append(obj_id)

    ordered: list[dict[str, Any]] = []
    for obj_id in expected_order + extras:
        item = best_by_id.get(obj_id)
        if item:
            ordered.append(item)
    return ordered


def _extract_challenged_objectives(note: str | None) -> list[str]:
    if not note:
        return []
    match = re.search(r"\[Challenged objectives:\s*([^\]]+)\]", note)
    if not match:
        return []
    return [part.strip() for part in match.group(1).split(",") if part.strip()]


def _packet_score(packet: dict[str, Any], target_control_id: str) -> float:
    classification_confidence = packet.get("classification_confidence") or 0.5
    score = _STRENGTH_WEIGHT.get(packet.get("evidence_strength"), 0.25)
    score += classification_confidence * 0.35
    score += _SOURCE_WEIGHT.get(packet.get("source_type"), 0.0)
    score += _ARTIFACT_BONUS.get(packet.get("artifact_type"), 0.0)
    score += min(packet.get("token_count", 0) / 800.0, 0.18)

    intent = packet.get("document_intent")
    if intent == "implements":
        score += 0.08
    elif intent == "plans":
        score -= 0.2
    elif intent in {"documents_gaps", "evaluates"}:
        score -= 0.1

    if target_control_id in (packet.get("control_ids") or []):
        score += 0.35
    if target_control_id in (packet.get("enhancement_ids") or []):
        score += 0.4
    if any(enh.startswith(f"{target_control_id}(") for enh in (packet.get("enhancement_ids") or [])):
        score += 0.15

    return round(score, 4)


def _packet_identity(packet: dict[str, Any]) -> tuple[Any, Any]:
    return (packet.get("unit_id"), packet.get("document_id"))


def _document_key(packet: dict[str, Any]) -> Any:
    return packet.get("document_id") or packet.get("filename") or packet.get("unit_id")


_OBJECTIVE_STOPWORDS = {
    "a", "an", "and", "are", "as", "at", "be", "by", "for", "from", "if", "in",
    "into", "is", "it", "of", "on", "or", "such", "that", "the", "their", "then",
    "there", "these", "this", "to", "when", "where", "which", "with", "within",
    "organization", "system", "systems", "shall", "must", "ensure", "provide",
    "using", "use", "used", "support", "supporting", "objective", "objectives",
    "review", "reviews", "document", "documents", "control", "controls",
}


def _tokenize_text(value: str | None) -> list[str]:
    if not value:
        return []
    return re.findall(r"[a-z0-9]+", value.lower())


def _normalize_control_reference(value: str | None) -> str:
    text = str(value or "").strip()
    match = re.match(r"^([A-Za-z]{2,3})-0*(\d+)(.*)$", text)
    if not match:
        return text.upper()
    family = match.group(1).upper()
    number = int(match.group(2))
    suffix = match.group(3)
    if suffix and suffix[0].isalpha():
        suffix = suffix[0].lower() + suffix[1:]
    return f"{family}-{number}{suffix}"


def _base_control_reference(value: str | None) -> str:
    normalized = _normalize_control_reference(value)
    return normalized.split("(", 1)[0]


def _reference_pattern(value: str | None) -> re.Pattern[str] | None:
    normalized = str(value or "").strip()
    if not normalized:
        return None
    parts = re.findall(r"[A-Za-z]+|\d+|[^A-Za-z\d\s]", normalized)
    if not parts:
        return None

    pattern_parts: list[str] = []
    for part in parts:
        if part.isdigit():
            pattern_parts.append(rf"0*{int(part)}")
        elif part.isalpha():
            pattern_parts.append(re.escape(part))
        else:
            pattern_parts.append(rf"\s*{re.escape(part)}\s*")
    pattern = "".join(pattern_parts)
    return re.compile(rf"(?<![A-Za-z0-9]){pattern}(?![A-Za-z0-9])", re.IGNORECASE)


def _packet_has_reference(packet: dict[str, Any], value: str | None) -> bool:
    pattern = _reference_pattern(value)
    if pattern is None:
        return False
    return bool(pattern.search(_packet_search_blob(packet)))


def _objective_branch_score(
    packet: dict[str, Any],
    *,
    target_control_id: str,
    objective_id: str,
) -> float:
    target_control = _normalize_control_reference(target_control_id)
    target_base = _base_control_reference(target_control)
    target_is_enhancement = "(" in target_control and ")" in target_control
    packet_controls = [_normalize_control_reference(item) for item in (packet.get("control_ids") or [])]
    packet_enhancements = [_normalize_control_reference(item) for item in (packet.get("enhancement_ids") or [])]
    packet_base_controls = {_base_control_reference(item) for item in [*packet_controls, *packet_enhancements] if item}
    exact_objective_match = _packet_has_reference(packet, objective_id)
    exact_control_match = _packet_has_reference(packet, target_control)

    score = 0.0
    if exact_objective_match:
        score += 0.85
    if exact_control_match:
        score += 0.28

    if target_is_enhancement:
        if target_control in packet_enhancements:
            score += 0.32
        elif target_base in packet_base_controls and packet_enhancements:
            sibling_matches = [item for item in packet_enhancements if _base_control_reference(item) == target_base]
            if sibling_matches:
                score -= 0.28
    else:
        sibling_matches = [item for item in packet_enhancements if _base_control_reference(item) == target_base]
        if sibling_matches and not exact_objective_match:
            score -= 0.18

    return round(score, 4)


def _objective_keywords(objective_text: str, control_title: str | None = None) -> list[str]:
    ordered: list[str] = []
    seen: set[str] = set()
    for token in _tokenize_text(" ".join(part for part in [control_title or "", objective_text] if part)):
        if len(token) <= 2 or token.isdigit() or token in _OBJECTIVE_STOPWORDS:
            continue
        if token in seen:
            continue
        seen.add(token)
        ordered.append(token)
    return ordered


def _packet_search_blob(packet: dict[str, Any]) -> str:
    return " ".join(
        str(part or "")
        for part in [
            packet.get("filename"),
            packet.get("section_path"),
            packet.get("document_type"),
            packet.get("document_intent"),
            packet.get("artifact_type"),
            packet.get("classification_explanation"),
            packet.get("content"),
        ]
    )


def _extract_packet_excerpt(content: str | None, keywords: list[str], max_chars: int = 420) -> str:
    raw = str(content or "").strip()
    if not raw:
        return ""
    collapsed = re.sub(r"\s+", " ", raw)
    lower = collapsed.lower()
    start_idx = 0
    for keyword in keywords:
        idx = lower.find(keyword.lower())
        if idx >= 0:
            start_idx = max(0, idx - 120)
            break
    excerpt = collapsed[start_idx:start_idx + max_chars].strip()
    if start_idx > 0:
        excerpt = "..." + excerpt
    if start_idx + max_chars < len(collapsed):
        excerpt = excerpt + "..."
    return excerpt


def _score_packet_for_objective(
    packet: dict[str, Any],
    *,
    target_control_id: str,
    objective_id: str,
    objective_text: str,
    control_title: str | None = None,
) -> tuple[float, list[str]]:
    keywords = _objective_keywords(objective_text, control_title)
    base_score = float(packet.get("relevance_score") or 0.0)
    packet_terms = set(_tokenize_text(_packet_search_blob(packet)))
    keyword_hits = [keyword for keyword in keywords if keyword in packet_terms]
    overlap_ratio = len(keyword_hits) / max(1, min(len(keywords), 8))
    triage_bonus = {
        "supporting": 0.08,
        "partial": 0.04,
        "contradictory": 0.06,
        "irrelevant": -0.12,
    }.get(packet.get("triage_role"), 0.0)
    intent_bonus = 0.0
    if packet.get("document_intent") in {"documents_gaps", "evaluates"}:
        intent_bonus += 0.03
    if packet.get("document_intent") == "implements":
        intent_bonus += 0.03
    branch_bonus = _objective_branch_score(
        packet,
        target_control_id=target_control_id,
        objective_id=objective_id,
    )
    objective_score = base_score + (overlap_ratio * 0.65) + triage_bonus + intent_bonus + branch_bonus
    return round(objective_score, 4), keyword_hits


def _objective_candidate_threshold(scored_packets: list[dict[str, Any]]) -> float:
    if not scored_packets:
        return 0.0
    top_score = max(float(packet.get("objective_relevance_score") or 0.0) for packet in scored_packets)
    return max(0.55, top_score * 0.42)


def _select_totality_packets_for_objective(
    considered_packets: list[dict[str, Any]],
    *,
    max_prompt_tokens: int = 12000,
) -> list[dict[str, Any]]:
    if not considered_packets:
        return []

    chosen: list[dict[str, Any]] = []
    chosen_ids: set[tuple[Any, Any]] = set()
    total_tokens = 0

    def _packet_prompt_tokens(packet: dict[str, Any]) -> int:
        excerpt = str(packet.get("llm_excerpt") or packet.get("content") or "")
        return max(80, len(excerpt) // 4 + 40)

    role_groups = {
        role: [packet for packet in considered_packets if packet.get("triage_role") == role]
        for role in ("supporting", "contradictory", "partial", "irrelevant")
    }
    for packets in role_groups.values():
        packets.sort(key=lambda item: float(item.get("objective_relevance_score") or 0.0), reverse=True)

    # First pass: ensure each role gets represented if present.
    for role in ("supporting", "contradictory", "partial", "irrelevant"):
        for packet in role_groups[role][:3]:
            identity = _packet_identity(packet)
            packet_tokens = _packet_prompt_tokens(packet)
            if identity in chosen_ids:
                continue
            if chosen and total_tokens + packet_tokens > max_prompt_tokens:
                continue
            chosen.append(packet)
            chosen_ids.add(identity)
            total_tokens += packet_tokens

    # Second pass: add the rest ordered by objective relevance.
    remaining = sorted(
        [packet for packet in considered_packets if _packet_identity(packet) not in chosen_ids],
        key=lambda item: float(item.get("objective_relevance_score") or 0.0),
        reverse=True,
    )
    for packet in remaining:
        identity = _packet_identity(packet)
        packet_tokens = _packet_prompt_tokens(packet)
        if identity in chosen_ids:
            continue
        if chosen and total_tokens + packet_tokens > max_prompt_tokens:
            continue
        chosen.append(packet)
        chosen_ids.add(identity)
        total_tokens += packet_tokens

    return chosen


def _merge_unique_packets(packet_groups: list[list[dict[str, Any]]]) -> list[dict[str, Any]]:
    merged: list[dict[str, Any]] = []
    seen: set[tuple[Any, Any]] = set()
    for group in packet_groups:
        for packet in group:
            identity = _packet_identity(packet)
            if identity in seen:
                continue
            seen.add(identity)
            merged.append(packet)
    return merged


def _build_objective_evidence_maps(
    control,
    objectives: list[str],
    candidate_packets: list[dict[str, Any]],
) -> dict[str, dict[str, Any]]:
    objective_maps: dict[str, dict[str, Any]] = {}
    for objective in objectives:
        objective_id, objective_text = _extract_objective_text(objective)
        if not objective_id:
            continue
        closure_contract = build_objective_closure_guidance(
            control_id=control.display_id,
            objective_id=objective_id,
            description=objective_text,
            system_name="the system",
            mode="production",
        )

        scored_packets: list[dict[str, Any]] = []
        for packet in candidate_packets:
            objective_score, keyword_hits = _score_packet_for_objective(
                packet,
                target_control_id=control.display_id,
                objective_id=objective_id,
                objective_text=objective_text,
                control_title=control.title,
            )
            contract_coverage = evaluate_contract_coverage(packet.get("content"), closure_contract)
            blended_score = max(
                objective_score,
                min(1.0, (0.55 * objective_score) + (0.65 * contract_coverage["score"])),
            )
            enriched_packet = {
                **packet,
                "packet_id": _packet_id(control.display_id, objective_id, packet),
                "objective_relevance_score": blended_score,
                "objective_relevance_base_score": objective_score,
                "objective_keyword_hits": keyword_hits,
                "contract_coverage_score": contract_coverage["score"],
                "contract_satisfied": contract_coverage["satisfied"],
                "contract_keyword_hits": contract_coverage["keyword_hits"],
                "contract_fact_hits": contract_coverage["fact_hits"],
                "contract_element_hits": contract_coverage["element_hits"],
            }
            enriched_packet["llm_excerpt"] = _extract_packet_excerpt(
                enriched_packet.get("content"),
                keyword_hits
                or contract_coverage["keyword_hits"][:3]
                or _objective_keywords(objective_text, control.title)[:3],
            )
            scored_packets.append(enriched_packet)

        scored_packets.sort(key=lambda item: float(item.get("objective_relevance_score") or 0.0), reverse=True)
        threshold = _objective_candidate_threshold(scored_packets)
        considered_packets = [
            packet
            for packet in scored_packets
            if packet.get("objective_keyword_hits")
            or packet.get("contract_satisfied")
            or float(packet.get("contract_coverage_score") or 0.0) >= 0.58
            or float(packet.get("objective_relevance_score") or 0.0) >= threshold
            or (
                packet.get("triage_role") in {"contradictory", "partial"}
                and float(packet.get("objective_relevance_score") or 0.0) >= max(0.45, threshold * 0.8)
            )
        ]
        if not considered_packets:
            considered_packets = scored_packets[:12]

        prompt_packets = _select_totality_packets_for_objective(considered_packets)
        aggregate_contract = evaluate_contract_coverage(
            " ".join(str(packet.get("content") or "") for packet in considered_packets[:10]),
            closure_contract,
        )
        best_contract_score = max((float(packet.get("contract_coverage_score") or 0.0) for packet in considered_packets), default=0.0)
        corroboration = _build_corroboration_summary(considered_packets)
        contradictory_documents = len({
            _document_key(packet) for packet in considered_packets if packet.get("triage_role") == "contradictory"
        })
        considered_documents = max(1, corroboration.get("total_documents", len(considered_packets)) or 1)
        objective_maps[objective_id] = {
            "objective_id": objective_id,
            "objective_text": objective_text,
            "objective_reference": objective,
            "considered_packets": considered_packets,
            "prompt_packets": prompt_packets,
            "corroboration": corroboration,
            "contradiction_ratio": contradictory_documents / considered_documents,
            "closure_contract": closure_contract,
            "contract_coverage": {
                **aggregate_contract,
                "best_packet_score": round(best_contract_score, 4),
            },
            "evidence_summary": {
                "candidate_packets": len(candidate_packets),
                "considered_packets": len(considered_packets),
                "prompt_packets": len(prompt_packets),
                "supporting_packets": sum(1 for packet in considered_packets if packet.get("triage_role") == "supporting"),
                "contradictory_packets": sum(1 for packet in considered_packets if packet.get("triage_role") == "contradictory"),
                "partial_packets": sum(1 for packet in considered_packets if packet.get("triage_role") == "partial"),
                "threshold": round(threshold, 4),
                "contract_coverage_score": aggregate_contract["score"],
                "contract_satisfied": aggregate_contract["satisfied"],
            },
        }
    return objective_maps


def _pick_diverse_packets(
    packets: list[dict[str, Any]],
    limit: int,
) -> list[dict[str, Any]]:
    if limit <= 0 or not packets:
        return []

    chosen: list[dict[str, Any]] = []
    seen_identities: set[tuple[Any, Any]] = set()
    seen_documents: set[Any] = set()

    for packet in packets:
        if len(chosen) >= limit:
            break
        identity = _packet_identity(packet)
        document_key = _document_key(packet)
        if identity in seen_identities or document_key in seen_documents:
            continue
        chosen.append(packet)
        seen_identities.add(identity)
        seen_documents.add(document_key)

    for packet in packets:
        if len(chosen) >= limit:
            break
        identity = _packet_identity(packet)
        if identity in seen_identities:
            continue
        chosen.append(packet)
        seen_identities.add(identity)

    return chosen


def _build_corroboration_summary(packets: list[dict[str, Any]]) -> dict[str, Any]:
    considered = [pkt for pkt in packets if pkt.get("triage_role") in {"supporting", "partial"}]
    supporting = [pkt for pkt in considered if pkt.get("triage_role") == "supporting"]
    contradictory = [pkt for pkt in packets if pkt.get("triage_role") == "contradictory"]
    total_documents = len({_document_key(packet) for packet in packets})

    document_map: dict[Any, dict[str, Any]] = {}
    for packet in considered:
        key = _document_key(packet)
        if key in document_map:
            continue
        document_map[key] = {
            "document_id": packet.get("document_id"),
            "filename": packet.get("filename"),
            "source_type": packet.get("source_type"),
            "artifact_type": packet.get("artifact_type"),
            "triage_role": packet.get("triage_role"),
        }

    supporting_document_keys = {_document_key(packet) for packet in supporting}
    supporting_documents = [
        details for key, details in document_map.items()
        if key in supporting_document_keys
    ]
    source_types = sorted({details.get("source_type") for details in supporting_documents if details.get("source_type")})
    artifact_types = sorted({details.get("artifact_type") for details in supporting_documents if details.get("artifact_type")})

    corroboration_strength = "none"
    if len(supporting_documents) >= 3 and len(source_types) >= 2:
        corroboration_strength = "multi_source"
    elif len(supporting_documents) >= 2:
        corroboration_strength = "multi_document"
    elif len(supporting_documents) == 1:
        corroboration_strength = "single_document"

    return {
        "supporting_units": len(supporting),
        "supporting_documents": len(supporting_documents),
        "considered_units": len(considered),
        "considered_documents": len(document_map),
        "total_documents": total_documents,
        "contradictory_units": len(contradictory),
        "source_types": source_types,
        "artifact_types": artifact_types,
        "cross_source": len(source_types) >= 2,
        "cross_artifact": len(artifact_types) >= 2,
        "corroboration_strength": corroboration_strength,
        "supporting_examples": supporting_documents[:6],
    }


def _apply_corroboration_bonus(
    status: str,
    confidence: float,
    corroboration: dict[str, Any],
) -> float:
    if status not in {"compliant", "partially_compliant"}:
        return confidence

    bonus = 0.0
    supporting_documents = corroboration.get("supporting_documents", 0)
    source_types = corroboration.get("source_types") or []
    artifact_types = corroboration.get("artifact_types") or []

    if supporting_documents >= 2:
        bonus += 0.02
    if supporting_documents >= 3:
        bonus += 0.02
    if len(source_types) >= 2:
        bonus += 0.02
    if len(artifact_types) >= 2:
        bonus += 0.01

    if bonus <= 0:
        return confidence

    cap = 0.95 if status == "compliant" else 0.90
    return round(min(cap, confidence + bonus), 2)


def _clamp(value: float, lower: float = 0.0, upper: float = 1.0) -> float:
    return max(lower, min(upper, value))


def _coerce_policy_runtime(policy_runtime: dict[str, Any] | None) -> dict[str, Any]:
    runtime = policy_runtime or {}
    thresholds = {
        **DEFAULT_THRESHOLDS,
        **(runtime.get("thresholds") or {}),
    }
    buckets = runtime.get("buckets") or {}
    return {
        "policy_id": runtime.get("policy_id"),
        "policy_version": runtime.get("policy_version"),
        "thresholds": thresholds,
        "buckets": buckets,
    }


def _parse_packet_source_index(source: Any) -> int | None:
    if isinstance(source, int):
        return source
    if isinstance(source, str):
        value = source.strip()
        if value.isdigit():
            return int(value)
        match = re.match(r"(?i)^(?:document|excerpt)\s+(\d+)\b", value)
        if match:
            return int(match.group(1))
    return None


def _resolve_objective_packet(obj: dict[str, Any], packets: list[dict[str, Any]]) -> dict[str, Any] | None:
    packet_id = str(obj.get("packet_id") or "").strip()
    if packet_id:
        for packet in packets:
            if str(packet.get("packet_id") or "").strip() == packet_id:
                return packet

    source = str(obj.get("source") or "").strip().lower()
    if source:
        for packet in packets:
            packet_id_value = str(packet.get("packet_id") or "").strip().lower()
            if packet_id_value and source == packet_id_value:
                return packet

    idx = _parse_packet_source_index(obj.get("source"))
    if idx is not None and 1 <= idx <= len(packets):
        return packets[idx - 1]

    evidence_quote = (obj.get("evidence_quote") or "").strip()
    for packet in packets:
        filename = str(packet.get("filename") or "").strip().lower()
        content = str(packet.get("content") or "")
        if source and filename and source in filename:
            return packet
        if evidence_quote and evidence_quote[:80] and evidence_quote[:80] in content:
            return packet
    return None


def _best_objective_packet(packets: list[dict[str, Any]]) -> dict[str, Any] | None:
    eligible = [
        packet for packet in packets
        if packet.get("triage_role") != "contradictory"
        and packet.get("document_intent") not in {"plans", "documents_gaps"}
    ]
    if not eligible:
        return None
    return max(
        eligible,
        key=lambda packet: (
            _EVIDENCE_STRENGTH_SCORE.get(packet.get("evidence_strength"), 0.20),
            float(packet.get("contract_coverage_score") or 0.0),
            float(packet.get("objective_relevance_score") or 0.0),
        ),
    )


def _deterministic_fallback_packet(
    *,
    obj: dict[str, Any],
    objective_map: dict[str, Any],
    prompt_packets: list[dict[str, Any]],
    considered_packets: list[dict[str, Any]],
) -> dict[str, Any] | None:
    if obj.get("met") not in {"yes", "partial", "no"}:
        return None
    contradiction_ratio = float(objective_map.get("contradiction_ratio") or 0.0)
    if contradiction_ratio >= 0.15:
        return None

    contract_coverage = objective_map.get("contract_coverage") or {}
    aggregate_score = float(contract_coverage.get("score") or 0.0)
    best_packet = _best_objective_packet(prompt_packets) or _best_objective_packet(considered_packets)
    if not best_packet:
        return None

    packet_contract = float(best_packet.get("contract_coverage_score") or 0.0)
    if obj.get("met") in {"yes", "partial"}:
        return best_packet
    if obj.get("met") == "no" and max(packet_contract, aggregate_score) < 0.55:
        return None
    if packet_contract < 0.58 and aggregate_score < 0.65:
        return None
    return best_packet


def _unique_packets(packet_groups: list[list[dict[str, Any]]]) -> list[dict[str, Any]]:
    unique: list[dict[str, Any]] = []
    seen: set[tuple[Any, Any] | str] = set()
    for packets in packet_groups:
        for packet in packets:
            packet_id = str(packet.get("packet_id") or "").strip()
            identity: tuple[Any, Any] | str = packet_id or _packet_identity(packet)
            if identity in seen:
                continue
            seen.add(identity)
            unique.append(packet)
    return unique


def _packet_citation(packet: dict[str, Any] | None, objective_id: str) -> list[dict[str, Any]]:
    if not packet:
        return []
    return [{
        "source": packet.get("filename") or "Assessment Evidence",
        "quote": (packet.get("llm_excerpt") or packet.get("content") or "")[:400],
        "relevance": objective_id,
        "packet_id": packet.get("packet_id"),
    }]


def _deterministic_objective_support(
    *,
    packet: dict[str, Any] | None,
    bucket: dict[str, Any],
    objective_map: dict[str, Any],
    evidence_quality: float,
    minimum_strength: float,
    contradiction_ratio: float,
) -> dict[str, Any]:
    """Conservative deterministic closure for strong current-state evidence."""
    if not packet:
        return {"status": "none", "reason": "no_resolved_packet"}
    if packet.get("triage_role") == "contradictory":
        return {"status": "none", "reason": "contradictory_packet"}
    if packet.get("document_intent") in {"plans", "documents_gaps"}:
        return {"status": "none", "reason": f"intent_{packet.get('document_intent')}"}
    if contradiction_ratio >= 0.20:
        return {"status": "none", "reason": "contradictory_evidence_present"}

    strength = packet.get("evidence_strength")
    source_type = packet.get("source_type")
    artifact_type = packet.get("artifact_type")
    relevance = float(packet.get("objective_relevance_score") or 0.0)
    contract_score = float(packet.get("contract_coverage_score") or 0.0)
    aggregate_contract = objective_map.get("contract_coverage") or {}
    aggregate_score = float(aggregate_contract.get("score") or 0.0)
    contract_satisfied = bool(packet.get("contract_satisfied") or aggregate_contract.get("satisfied"))

    high_quality = evidence_quality >= max(0.58, minimum_strength * 0.82)
    strong_current_evidence = (
        source_type in {"project", "common_control"}
        and strength in {"strong", "moderate"}
        and packet.get("document_intent") == "implements"
        and artifact_type in {"technical_config", "test_evidence", "implementation_statement", "procedure", "policy"}
    )
    objective_specific = relevance >= 1.15 or contract_score >= 0.58 or aggregate_score >= 0.58

    if contract_satisfied and evidence_quality >= max(0.50, minimum_strength * 0.70):
        return {"status": "met", "reason": "contract_satisfied"}
    if strong_current_evidence and objective_specific and high_quality:
        return {"status": "met", "reason": "strong_current_objective_evidence"}
    if strong_current_evidence and objective_specific and evidence_quality >= 0.45:
        return {"status": "partial", "reason": "current_objective_evidence_below_bucket_strength"}
    return {"status": "none", "reason": "deterministic_threshold_not_met"}


def _objective_evidence_quality(
    packet: dict[str, Any] | None,
    bucket: dict[str, Any],
    obj: dict[str, Any],
) -> float:
    if packet is None:
        return 0.18 if obj.get("met") == "no" else 0.28

    quality = _EVIDENCE_STRENGTH_SCORE.get(packet.get("evidence_strength"), 0.35)
    quality += _ARTIFACT_QUALITY_SCORE.get(packet.get("artifact_type"), 0.0)
    quality += _SOURCE_QUALITY_SCORE.get(packet.get("source_type"), 0.0)
    if obj.get("evidence_quote"):
        quality += 0.05
    coverage_score = float((packet or {}).get("contract_coverage_score") or 0.0)
    if coverage_score > 0:
        quality += min(0.16, 0.18 * coverage_score)
    if (packet or {}).get("contract_satisfied"):
        quality += 0.08
    if packet.get("document_intent") == "plans":
        quality = min(quality, bucket.get("future_state_cap") or 0.40)
    elif packet.get("document_intent") in {"documents_gaps", "evaluates"}:
        quality = max(0.10, quality - 0.20)
    return round(_clamp(quality, 0.05, 1.0), 4)


def _build_objective_rationale(
    *,
    obj: dict[str, Any],
    bucket: dict[str, Any],
    bucket_key: str,
    bucket_modifier: str | None,
    effective_support: float,
    evidence_quality: float,
    contradiction_ratio: float,
    packet: dict[str, Any] | None,
    critical: bool,
    manual_flags: list[str],
) -> str:
    parts = [
        f"Bucket={bucket_key}",
        f"weight={bucket.get('objective_weight', 1.0):.2f}",
        f"effective_support={effective_support:.2f}",
        f"evidence_quality={evidence_quality:.2f}",
    ]
    if bucket_modifier:
        parts.append(f"context={bucket_modifier}")
    if contradiction_ratio > 0:
        parts.append(f"contradiction={contradiction_ratio:.2f}")
    if critical:
        parts.append("critical=true")
    if packet and packet.get("source_type"):
        parts.append(f"source_type={packet.get('source_type')}")
    if packet and packet.get("artifact_type"):
        parts.append(f"artifact_type={packet.get('artifact_type')}")
    if packet and packet.get("document_intent"):
        parts.append(f"intent={packet.get('document_intent')}")
    if manual_flags:
        parts.append(f"manual_review={','.join(sorted(set(manual_flags)))}")
    return "; ".join(parts)


def _policy_based_verdict(
    *,
    assessment_id: int,
    control,
    objectives: list[str],
    gap_analysis: list[dict[str, Any]],
    objective_evidence_maps: dict[str, dict[str, Any]],
    corroboration: dict[str, Any],
    policy_runtime: dict[str, Any] | None,
) -> dict[str, Any]:
    runtime = _coerce_policy_runtime(policy_runtime)
    thresholds = runtime["thresholds"]
    bucket_map = runtime["buckets"]
    default_bucket = bucket_map.get("procedure_execution", {})

    objective_aliases = _build_objective_id_aliases(objectives)
    obj_text_by_id: dict[str, str] = {}
    for objective in objectives:
        obj_id, objective_text = _extract_objective_text(objective)
        canonical_id = _canonical_objective_id(obj_id, objective_aliases)
        if canonical_id:
            obj_text_by_id[canonical_id] = objective_text
    evidence_map_aliases = {
        _objective_alias_key(objective_id): objective_id
        for objective_id in objective_evidence_maps
        if _objective_alias_key(objective_id)
    }
    all_prompt_packets = _unique_packets([
        objective_map.get("prompt_packets") or []
        for objective_map in objective_evidence_maps.values()
    ])
    all_considered_packets = _unique_packets([
        objective_map.get("considered_packets") or []
        for objective_map in objective_evidence_maps.values()
    ])
    objective_rows: list[dict[str, Any]] = []
    objective_details: list[dict[str, Any]] = []
    shall_failures: list[str] = []
    critical_failures: list[str] = []
    manual_review_reasons: set[str] = set()
    weighted_support = 0.0
    weighted_possible = 0.0
    weighted_evidence = 0.0
    weighted_contradiction = 0.0

    for obj in gap_analysis:
        raw_objective_id = str(obj.get("objective_id") or "").strip()
        objective_id = _canonical_objective_id(raw_objective_id, objective_aliases)
        if not objective_id:
            continue

        objective_map_key = objective_id
        objective_map = objective_evidence_maps.get(objective_map_key)
        if objective_map is None:
            alias_key = _objective_alias_key(raw_objective_id) or _objective_alias_key(objective_id)
            objective_map_key = evidence_map_aliases.get(alias_key, objective_id)
            objective_map = objective_evidence_maps.get(objective_map_key, {})
            if objective_map_key != objective_id:
                objective_id = _canonical_objective_id(objective_map_key, objective_aliases)
        objective_text = obj_text_by_id.get(objective_id, obj_text_by_id.get(objective_map_key, ""))
        bucket_context = resolve_bucket_context(control.family_id, objective_text, control.title)
        bucket_key = bucket_context["bucket_key"]
        scoring_bucket_key = bucket_context["primary_bucket_key"]
        bucket = (
            bucket_map.get(scoring_bucket_key)
            or bucket_map.get(bucket_key)
            or default_bucket
        )
        considered_packets = objective_map.get("considered_packets") or []
        prompt_packets = objective_map.get("prompt_packets") or considered_packets
        packet = _resolve_objective_packet(obj, prompt_packets) or _resolve_objective_packet(obj, considered_packets)
        packet_resolution_scope = "objective" if packet is not None else None
        if packet is None:
            packet = _resolve_objective_packet(obj, all_prompt_packets) or _resolve_objective_packet(obj, all_considered_packets)
            packet_resolution_scope = "control" if packet is not None else None
        citation_fallback_applied = False
        if packet is None:
            packet = _deterministic_fallback_packet(
                obj=obj,
                objective_map=objective_map,
                prompt_packets=prompt_packets,
                considered_packets=considered_packets,
            )
            citation_fallback_applied = packet is not None
            packet_resolution_scope = "fallback" if packet is not None else None
        evidence_quality = _objective_evidence_quality(packet, bucket, obj)
        minimum_strength = float(bucket.get("minimum_evidence_strength") or 0.50)
        contradiction_penalty = float(bucket.get("contradiction_penalty") or 0.0)
        weight = float(bucket.get("objective_weight") or 1.0)
        critical = bool(bucket.get("critical_by_default"))
        contract_coverage = objective_map.get("contract_coverage") or {}
        contract_score = float(contract_coverage.get("score") or 0.0)
        contract_satisfied = bool(contract_coverage.get("satisfied"))
        base_score = {
            "yes": 1.0,
            "partial": 0.5,
            "no": 0.0,
        }.get(obj.get("met"), 0.0)
        if contract_satisfied:
            base_score = max(base_score, 1.0)
        elif contract_score >= 0.70:
            base_score = max(base_score, 0.85)
        elif contract_score >= 0.58:
            base_score = max(base_score, 0.65)
        quality_factor = 1.0 if evidence_quality >= minimum_strength else max(0.20, evidence_quality / max(minimum_strength, 0.01))
        contradiction_ratio_for_objective = float(objective_map.get("contradiction_ratio") or 0.0)
        contradiction_for_objective = contradiction_ratio_for_objective if obj.get("met") in {"yes", "partial"} else 0.0
        deterministic_support = _deterministic_objective_support(
            packet=packet,
            bucket=bucket,
            objective_map=objective_map,
            evidence_quality=evidence_quality,
            minimum_strength=minimum_strength,
            contradiction_ratio=contradiction_ratio_for_objective,
        )
        effective_met = obj.get("met")
        deterministic_override = False
        if deterministic_support["status"] == "met":
            effective_met = "yes"
            base_score = max(base_score, 1.0)
            deterministic_override = obj.get("met") != "yes"
        elif deterministic_support["status"] == "partial" and effective_met == "no":
            effective_met = "partial"
            base_score = max(base_score, 0.5)
            deterministic_override = True
        contradiction_for_objective = contradiction_ratio_for_objective if effective_met in {"yes", "partial"} else 0.0
        effective_support = max(0.0, (base_score * quality_factor) - (contradiction_for_objective * contradiction_penalty))
        if contract_satisfied and contradiction_for_objective < 0.15:
            effective_support = max(effective_support, 0.92)
        elif contract_score >= 0.70 and contradiction_for_objective < 0.15:
            effective_support = max(effective_support, 0.82)
        elif contract_score >= 0.58 and contradiction_for_objective < 0.20:
            effective_support = max(effective_support, 0.60)

        inherited_only = bool(bucket_context["inherited_context"]) or (
            packet is not None and packet.get("source_type") == "common_control"
        )
        compensating_only = bool(bucket_context["compensating_context"])
        bucket_modifier = (
            "compensating"
            if compensating_only
            else "inherited"
            if inherited_only
            else None
        )
        manual_flags: list[str] = []
        if evidence_quality < float(thresholds.get("manual_review_weak_evidence_threshold", 0.45)) and effective_met in {"yes", "partial"}:
            manual_flags.append("weak_evidence")
            manual_review_reasons.add("weak_evidence")
        if contradiction_for_objective >= float(thresholds.get("manual_review_contradiction_threshold", 0.20)):
            manual_flags.append("contradiction")
            manual_review_reasons.add("contradictory_evidence")
        if contract_score < 0.45 and effective_met in {"yes", "partial"} and deterministic_support["status"] != "met":
            manual_flags.append("objective_not_closed")
            manual_review_reasons.add("objective_not_closed")
        if inherited_only and bool(thresholds.get("manual_review_inheritance_without_authority", True)):
            manual_flags.append("inherited_only")
            manual_review_reasons.add("inherited_support_requires_review")
        if compensating_only and bool(thresholds.get("manual_review_compensating_without_authority", True)):
            manual_flags.append("compensating_only")
            manual_review_reasons.add("compensating_support_requires_review")

        if effective_met == "no":
            shall_failures.append(objective_id)

        if effective_met == "no" or effective_support < 0.20:
            objective_status = "not_met"
        elif effective_support >= 0.85 and evidence_quality >= minimum_strength:
            objective_status = "met"
        elif effective_support >= 0.35:
            objective_status = "partially_met"
        else:
            objective_status = "not_met"
        if deterministic_support["status"] == "met" and contradiction_for_objective < 0.15:
            objective_status = "met"
        elif contract_satisfied and contradiction_for_objective < 0.15 and evidence_quality >= max(0.45, minimum_strength * 0.8):
            objective_status = "met"
        elif objective_status == "not_met" and contract_score >= 0.58 and contradiction_for_objective < 0.20:
            objective_status = "partially_met"

        if critical and objective_status == "not_met":
            critical_failures.append(objective_id)

        objective_confidence = _clamp(
            0.20 + (0.45 * effective_support) + (0.35 * evidence_quality) - (0.20 * contradiction_for_objective),
            0.10,
            0.95,
        )
        supporting = _objective_supporting_citation(obj) or _packet_citation(packet, objective_id)
        contradictory_packets = [pkt for pkt in considered_packets if pkt.get("triage_role") == "contradictory"]
        contradictory_citations = [
            {
                "source": pkt.get("filename") or "Assessment Evidence",
                "quote": (pkt.get("llm_excerpt") or pkt.get("content") or "")[:240],
                "relevance": "contradictory evidence",
            }
            for pkt in contradictory_packets
        ][:3]

        objective_rows.append({
            "assessment_id": assessment_id,
            "control_id": control.display_id,
            "objective_id": objective_id,
            "objective_text": objective_text,
            "status": objective_status,
            "rationale": _build_objective_rationale(
                obj=obj,
                bucket=bucket,
                bucket_key=scoring_bucket_key,
                bucket_modifier=bucket_modifier,
                effective_support=effective_support,
                evidence_quality=evidence_quality,
                contradiction_ratio=contradiction_for_objective,
                packet=packet,
                critical=critical,
                manual_flags=manual_flags,
            ),
            "supporting_citations": supporting or None,
            "contradictory_citations": contradictory_citations or None,
            "missing_evidence": None if objective_status == "met" else obj.get("gap"),
            "confidence_score": round(objective_confidence, 2),
            "raw_llm_result": dict(obj),
            "adjudication_json": {
                "raw_objective_id": raw_objective_id if raw_objective_id != objective_id else None,
                "packet_id": packet.get("packet_id") if packet else None,
                "packet_resolved": packet is not None,
                "packet_resolution_scope": packet_resolution_scope,
                "citation_fallback_applied": citation_fallback_applied,
                "llm_met": obj.get("met"),
                "effective_met": effective_met,
                "deterministic_support": deterministic_support,
                "deterministic_override": deterministic_override,
                "contract_score": round(contract_score, 4),
                "aggregate_contract_score": round(float((objective_map.get("contract_coverage") or {}).get("score") or 0.0), 4),
                "source_type": packet.get("source_type") if packet else None,
                "artifact_type": packet.get("artifact_type") if packet else None,
                "evidence_strength": packet.get("evidence_strength") if packet else None,
            },
        })
        objective_details.append({
            "objective_id": objective_id,
            "bucket_key": scoring_bucket_key,
            "bucket_context_key": bucket_key,
            "bucket_modifier": bucket_modifier,
            "weight": round(weight, 3),
            "base_result": obj.get("met"),
            "effective_result": effective_met,
            "effective_status": objective_status,
            "effective_support": round(effective_support, 3),
            "evidence_quality": round(evidence_quality, 3),
            "minimum_evidence_strength": round(minimum_strength, 3),
            "critical": critical,
            "contradiction_ratio": round(contradiction_for_objective, 3),
            "source_type": packet.get("source_type") if packet else None,
            "artifact_type": packet.get("artifact_type") if packet else None,
            "packet_id": packet.get("packet_id") if packet else None,
            "document_intent": packet.get("document_intent") if packet else None,
            "inherited_context": inherited_only,
            "compensating_context": compensating_only,
            "evidence_map_summary": objective_map.get("evidence_summary") or {},
            "objective_corroboration": objective_map.get("corroboration") or {},
            "manual_flags": manual_flags,
            "contract_coverage": contract_coverage,
            "citation_fallback_applied": citation_fallback_applied,
            "deterministic_support": deterministic_support,
            "deterministic_override": deterministic_override,
        })

        weighted_possible += weight
        weighted_support += effective_support * weight
        weighted_evidence += evidence_quality * weight
        weighted_contradiction += contradiction_for_objective * weight

    support_ratio = weighted_support / weighted_possible if weighted_possible else 0.0
    evidence_quality_index = weighted_evidence / weighted_possible if weighted_possible else 0.0
    contradiction_index = weighted_contradiction / weighted_possible if weighted_possible else 0.0

    has_positive_support = any(row["status"] in {"met", "partially_met"} for row in objective_rows)
    unresolved_objectives = [
        row["objective_id"]
        for row in objective_rows
        if row["status"] != "met"
    ]
    compliant_allowed = (
        not unresolved_objectives
        and not (bool(thresholds.get("critical_failure_blocks_compliant", True)) and critical_failures)
    )
    if (
        compliant_allowed
        and support_ratio >= float(thresholds.get("compliant_threshold", 0.85))
        and evidence_quality_index >= float(thresholds.get("minimum_evidence_quality_for_compliant", 0.65))
        and contradiction_index <= float(thresholds.get("max_contradiction_for_compliant", 0.15))
    ):
        status = "compliant"
    elif support_ratio >= float(thresholds.get("partial_threshold", 0.45)) or has_positive_support:
        status = "partially_compliant"
    else:
        status = "non_compliant"

    confidence_alignment = support_ratio if status != "non_compliant" else (1.0 - support_ratio)
    confidence = _clamp(
        0.28 + (0.38 * confidence_alignment) + (0.28 * evidence_quality_index) - (0.18 * contradiction_index),
        0.10,
        0.94,
    )
    confidence = _apply_corroboration_bonus(status, round(confidence, 2), corroboration)

    total_considered_packets = sum(
        int((objective_evidence_maps.get(row["objective_id"]) or {}).get("evidence_summary", {}).get("considered_packets", 0))
        for row in objective_rows
    )
    total_prompt_packets = sum(
        int((objective_evidence_maps.get(row["objective_id"]) or {}).get("evidence_summary", {}).get("prompt_packets", 0))
        for row in objective_rows
    )

    met_count = sum(1 for row in objective_rows if row["status"] == "met")
    partial_count = sum(1 for row in objective_rows if row["status"] == "partially_met")
    not_met_count = sum(1 for row in objective_rows if row["status"] == "not_met")
    supporting_documents = int(corroboration.get("supporting_documents", 0) or 0)
    unresolved_count = len(unresolved_objectives)
    critical_count = len(critical_failures)
    if unresolved_count:
        unresolved_sentence = (
            f"{unresolved_count} objective(s) still need evidence review"
            + (f", including {critical_count} critical objective(s)." if critical_count else ".")
        )
    else:
        unresolved_sentence = "All objectives are supported by the reviewed evidence."
    evidence_summary = (
        f"Reviewed {len(objective_rows)} objective(s) against policy v{runtime.get('policy_version') or 1}: "
        f"{met_count} met, {partial_count} partially met, and {not_met_count} not met. "
        f"{unresolved_sentence} "
        f"The determination cites evidence from {supporting_documents} supporting document(s)."
    )

    return {
        "status": status,
        "confidence": confidence,
        "shall_failures": shall_failures,
        "critical_failures": critical_failures,
        "unresolved_objectives": unresolved_objectives,
        "needs_manual_review": bool(manual_review_reasons),
        "manual_review_reasons": sorted(manual_review_reasons),
        "objective_rows": objective_rows,
        "objective_details": objective_details,
        "objective_summary": {
            "total": len(objective_rows),
            "met": sum(1 for row in objective_rows if row["status"] == "met"),
            "partial": sum(1 for row in objective_rows if row["status"] == "partially_met"),
            "not_met": sum(1 for row in objective_rows if row["status"] == "not_met"),
            "shall_failures": shall_failures,
            "critical_failures": critical_failures,
            "unresolved_objectives": unresolved_objectives,
            "weighted_support_score": round(support_ratio, 3),
            "evidence_quality_index": round(evidence_quality_index, 3),
            "contradiction_index": round(contradiction_index, 3),
            "policy_id": runtime.get("policy_id"),
            "policy_version": runtime.get("policy_version"),
            "manual_review_reasons": sorted(manual_review_reasons),
            "corroboration": corroboration,
            "review_mode": "objective_totality_ingested_evidence_v2",
            "totality_review": {
                "objective_count": len(objective_rows),
                "total_considered_packet_assignments": total_considered_packets,
                "total_prompt_packet_assignments": total_prompt_packets,
            },
            "objective_details": objective_details,
        },
        "evidence_summary": evidence_summary,
    }


def _effective_gap_analysis_from_objective_rows(
    gap_analysis: list[dict[str, Any]],
    objective_rows: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """Align narrative/challenge inputs with the code-authoritative objective verdict."""
    rows_by_id = {row.get("objective_id"): row for row in objective_rows}
    rows_by_alias = {
        _objective_alias_key(str(row.get("objective_id") or "")): row
        for row in objective_rows
        if _objective_alias_key(str(row.get("objective_id") or ""))
    }
    effective: list[dict[str, Any]] = []
    for obj in gap_analysis:
        objective_id = _normalize_objective_id(obj.get("objective_id"))
        row = rows_by_id.get(objective_id) or rows_by_alias.get(_objective_alias_key(obj.get("objective_id")))
        if not row:
            effective.append(obj)
            continue
        citations = row.get("supporting_citations") or []
        citation = citations[0] if citations else {}
        if row.get("status") == "met":
            effective.append({
                **obj,
                "objective_id": row.get("objective_id") or objective_id,
                "met": "yes",
                "evidence_quote": citation.get("quote") or obj.get("evidence_quote"),
                "source": citation.get("source") or obj.get("source"),
                "packet_id": citation.get("packet_id") or obj.get("packet_id"),
                "gap": None,
            })
        elif row.get("status") == "partially_met":
            effective.append({
                **obj,
                "objective_id": row.get("objective_id") or objective_id,
                "met": "partial" if obj.get("met") != "yes" else obj.get("met"),
                "evidence_quote": citation.get("quote") or obj.get("evidence_quote"),
                "source": citation.get("source") or obj.get("source"),
                "packet_id": citation.get("packet_id") or obj.get("packet_id"),
                "gap": row.get("missing_evidence") or obj.get("gap"),
            })
        else:
            effective.append({
                **obj,
                "objective_id": row.get("objective_id") or objective_id,
                "met": "no",
                "gap": row.get("missing_evidence") or obj.get("gap"),
            })
    return effective


async def build_scope_document_ids(project_id: int, db: AsyncSession) -> list[int]:
    indexed_statuses = ("complete", "indexed")

    linked_provider_ids = (
        await db.execute(
            select(ProjectCommonProvider.provider_id).where(ProjectCommonProvider.project_id == project_id)
        )
    ).scalars().all()

    scope_conditions = [
        Document.project_id == project_id,
        Document.policy_library_id.is_not(None),
        Document.procedure_library_id.is_not(None),
    ]
    if linked_provider_ids:
        scope_conditions.append(Document.provider_id.in_(linked_provider_ids))

    latest_runs = (
        select(
            IngestionRun.document_id.label("document_id"),
            func.max(IngestionRun.id).label("run_id"),
        )
        .where(IngestionRun.status == "complete")
        .group_by(IngestionRun.document_id)
        .subquery()
    )
    scope_query = (
        select(Document.id)
        .join(latest_runs, latest_runs.c.document_id == Document.id)
        .join(IngestionRun, IngestionRun.id == latest_runs.c.run_id)
        .where(
        Document.parse_status.in_(indexed_statuses),
        or_(*scope_conditions),
        or_(Document.autogenerated.is_(False), Document.evidence_eligible.is_(True)),
        IngestionRun.quality_status == "passed",
        IngestionRun.readiness_eligible.is_(True),
    ))
    return list((await db.execute(scope_query)).scalars().all())


async def get_scope_evidence_readiness(project_id: int, db: AsyncSession) -> dict[str, Any]:
    """Build an assessment scope without letting newly degraded ingestion pass silently."""
    indexed_statuses = ("complete", "indexed")
    linked_provider_ids = (
        await db.execute(
            select(ProjectCommonProvider.provider_id).where(ProjectCommonProvider.project_id == project_id)
        )
    ).scalars().all()
    scope_conditions = [
        Document.project_id == project_id,
        Document.policy_library_id.is_not(None),
        Document.procedure_library_id.is_not(None),
    ]
    if linked_provider_ids:
        scope_conditions.append(Document.provider_id.in_(linked_provider_ids))

    latest_runs = (
        select(
            IngestionRun.document_id.label("document_id"),
            func.max(IngestionRun.id).label("run_id"),
        )
        .where(IngestionRun.status == "complete")
        .group_by(IngestionRun.document_id)
        .subquery()
    )
    rows = (
        await db.execute(
            select(Document, IngestionRun)
            .join(latest_runs, latest_runs.c.document_id == Document.id)
            .join(IngestionRun, IngestionRun.id == latest_runs.c.run_id)
            .where(
                Document.parse_status.in_(indexed_statuses),
                or_(*scope_conditions),
                or_(Document.autogenerated.is_(False), Document.evidence_eligible.is_(True)),
            )
        )
    ).all()

    # A project assessment must not silently freeze a partial upload set while
    # other project-owned documents are still queued, processing, or failed.
    # Shared libraries remain point-in-time sources: only their completed,
    # eligible documents enter the frozen scope, so unrelated library work does
    # not block this project.
    latest_project_runs = (
        select(
            IngestionRun.document_id.label("document_id"),
            func.max(IngestionRun.id).label("run_id"),
        )
        .group_by(IngestionRun.document_id)
        .subquery()
    )
    project_document_runs = (
        await db.execute(
            select(Document, IngestionRun)
            .outerjoin(latest_project_runs, latest_project_runs.c.document_id == Document.id)
            .outerjoin(IngestionRun, IngestionRun.id == latest_project_runs.c.run_id)
            .where(
                Document.project_id == project_id,
                or_(Document.autogenerated.is_(False), Document.evidence_eligible.is_(True)),
            )
        )
    ).all()
    unready = _unready_project_documents(project_document_runs)
    degraded = [
        {
            "document_id": document.id,
            "filename": document.filename,
            "run_id": run.id,
            "fallback_stages": run.fallback_stages or [],
        }
        for document, run in rows
        if (run.quality_status != "passed" or not run.readiness_eligible)
        and not is_legacy_unverified_ingestion(run.fallback_stages)
    ]
    legacy_unverified = [
        {
            "document_id": document.id,
            "filename": document.filename,
            "run_id": run.id,
            "fallback_stages": run.fallback_stages or [],
        }
        for document, run in rows
        if is_legacy_unverified_ingestion(run.fallback_stages)
    ]
    eligible_entries = sorted(
        (
            {
                "document_id": document.id,
                "file_hash": document.file_hash,
                "ingestion_run_id": run.id,
                "quality_status": run.quality_status,
                "legacy_unverified": is_legacy_unverified_ingestion(run.fallback_stages),
            }
            for document, run in rows
            if is_assessment_ready_ingestion(run)
        ),
        key=lambda item: item["document_id"],
    )
    eligible_ids = [entry["document_id"] for entry in eligible_entries]
    scope_fingerprint = evidence_scope_fingerprint(eligible_entries)
    return {
        "ready": bool(eligible_ids) and not degraded and not unready,
        "eligible_document_ids": eligible_ids,
        "eligible_document_count": len(eligible_ids),
        "eligible_documents": eligible_entries,
        "scope_fingerprint": scope_fingerprint,
        "degraded_documents": degraded,
        "unready_documents": unready,
        "unready_document_count": len(unready),
        "legacy_unverified_documents": legacy_unverified,
        "legacy_unverified_document_count": len(legacy_unverified),
    }


async def preload_evidence_index(
    project_id: int,
    scope_doc_ids: list[int],
    db: AsyncSession,
    max_packets_per_control: int | None = 120,
    scope_run_ids: list[int] | None = None,
) -> dict[str, list[dict[str, Any]]]:
    if not scope_doc_ids:
        return {}

    query = (
        select(EvidenceUnit, EvidenceClassification, Document)
        .join(Document, Document.id == EvidenceUnit.document_id)
        .outerjoin(EvidenceClassification, EvidenceClassification.unit_id == EvidenceUnit.id)
        .where(Document.id.in_(scope_doc_ids))
    )
    if scope_run_ids:
        query = query.where(EvidenceUnit.run_id.in_(scope_run_ids))
    else:
        latest_runs = (
            select(
                IngestionRun.document_id.label("document_id"),
                func.max(IngestionRun.id).label("run_id"),
            )
            .where(
                IngestionRun.status == "complete",
                IngestionRun.document_id.in_(scope_doc_ids),
            )
            .group_by(IngestionRun.document_id)
            .subquery()
        )
        query = query.join(latest_runs, latest_runs.c.run_id == EvidenceUnit.run_id)

    result = await db.execute(query)

    by_control: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for unit, cls, doc in result.all():
        control_ids = list((cls.control_ids if cls else None) or [])
        enhancement_ids = list((cls.enhancement_ids if cls else None) or [])
        target_keys = set(control_ids)
        for enh in enhancement_ids:
            target_keys.add(enh)
            target_keys.add(enh.split("(")[0])

        profile = normalize_autogenerated_profile(
            doc,
            cls.artifact_type if cls else None,
            cls.evidence_strength if cls else None,
            cls.evidence_language_type if cls else None,
        )

        packet = {
            "unit_id": unit.id,
            "document_id": doc.id,
            "content": unit.content,
            "filename": doc.filename or "Unknown",
            "document_type": doc.document_type or "other",
            "document_intent": doc.document_intent or "other",
            "date": doc.created_at.strftime("%Y-%m-%d") if doc.created_at else None,
            "source_type": _source_type_for_doc(doc, project_id),
            "artifact_type": profile["artifact_type"],
            "evidence_strength": profile["evidence_strength"],
            "evidence_language_type": profile["evidence_language_type"],
            "classification_confidence": cls.model_confidence if cls else 0.0,
            "classification_explanation": (cls.explanation or "") if cls else "",
            "section_path": unit.section_path,
            "token_count": unit.token_count or max(1, len(unit.content) // 4),
            "page_numbers": unit.page_numbers or [],
            "control_ids": control_ids,
            "enhancement_ids": enhancement_ids,
            "triage_role": _triage_role(cls, doc) if cls else "supporting",
        }

        all_item = dict(packet)
        all_item["relevance_score"] = float(all_item.get("classification_confidence") or 0.0)
        by_control["__all__"].append(all_item)

        if not target_keys:
            continue

        for key in target_keys:
            item = dict(packet)
            item["relevance_score"] = _packet_score(item, key)
            by_control[key].append(item)

    for key, packets in by_control.items():
        packets.sort(key=lambda item: item["relevance_score"], reverse=True)
        seen: set[tuple[int | None, int | None]] = set()
        deduped = []
        for item in packets:
            packet_key = (item.get("unit_id"), item.get("document_id"))
            if packet_key in seen:
                continue
            seen.add(packet_key)
            deduped.append(item)
            if max_packets_per_control is not None and len(deduped) >= max_packets_per_control:
                break
        by_control[key] = deduped

    return by_control


def _select_packets_for_assessment(
    packets: list[dict[str, Any]],
    max_supporting: int = 8,
    max_partial: int = 3,
    max_contradictory: int = 3,
    max_irrelevant: int = 1,
    max_tokens: int = 5200,
) -> list[dict[str, Any]]:
    selected: list[dict[str, Any]] = []
    total_tokens = 0
    for role, limit in (
        ("supporting", max_supporting),
        ("partial", max_partial),
        ("contradictory", max_contradictory),
        ("irrelevant", max_irrelevant),
    ):
        role_packets = [pkt for pkt in packets if pkt.get("triage_role") == role]
        role_packets = _pick_diverse_packets(role_packets, limit)
        for pkt in role_packets:
            pkt_tokens = pkt.get("token_count", 0)
            if selected and total_tokens + pkt_tokens > max_tokens:
                continue
            selected.append(pkt)
            total_tokens += pkt_tokens
    return selected


def _objective_supporting_citation(obj: dict[str, Any]) -> list[dict[str, Any]]:
    if not obj.get("evidence_quote"):
        return []
    return [{
        "source": obj.get("source") or "Assessment Evidence",
        "quote": obj.get("evidence_quote"),
        "relevance": obj.get("objective_id"),
    }]


async def _run_objective_totality_review(
    control_id: str,
    control_title: str,
    objective_maps: dict[str, dict[str, Any]],
    system_context: str,
    llm,
) -> list[dict[str, Any]]:
    ordered_maps = list(objective_maps.values())
    objective_call_semaphore = asyncio.Semaphore(_resolve_objective_review_concurrency(llm))

    async def evaluate_objective(objective_map: dict[str, Any]) -> dict[str, Any]:
        async with objective_call_semaphore:
            objective_reference = objective_map["objective_reference"]
            packets = objective_map["prompt_packets"] or objective_map["considered_packets"]
            result = await run_gap_analysis(
                control_id=control_id,
                control_title=control_title,
                objectives=[objective_reference],
                chunks=packets,
                system_context=system_context,
                llm=llm,
            )
            if result:
                row = result[0]
            else:
                objective_id, _objective_text = _extract_objective_text(objective_reference)
                row = {
                    "objective_id": objective_id,
                    "met": "no",
                    "evidence_quote": None,
                    "source": None,
                    "gap": "Unable to complete objective-level evidence adjudication.",
                }
            row["objective_evidence_summary"] = objective_map["evidence_summary"]
            return row

    results = await asyncio.gather(*[evaluate_objective(item) for item in ordered_maps]) if ordered_maps else []
    return list(results)


async def _reset_control_stage_rows(assessment_id: int, control_id: str, db: AsyncSession) -> None:
    await db.execute(
        delete(AssessmentEvidenceTriage).where(
            AssessmentEvidenceTriage.assessment_id == assessment_id,
            AssessmentEvidenceTriage.control_id == control_id,
        )
    )
    await db.execute(
        delete(ObjectiveDetermination).where(
            ObjectiveDetermination.assessment_id == assessment_id,
            ObjectiveDetermination.control_id == control_id,
        )
    )
    await db.execute(
        delete(ObjectiveEvidenceReview).where(
            ObjectiveEvidenceReview.assessment_id == assessment_id,
            ObjectiveEvidenceReview.control_id == control_id,
        )
    )
    await db.execute(
        delete(ControlDetermination).where(
            ControlDetermination.assessment_id == assessment_id,
            ControlDetermination.control_id == control_id,
        )
    )
    await db.execute(
        delete(AssessmentChallenge).where(
            AssessmentChallenge.assessment_id == assessment_id,
            AssessmentChallenge.control_id == control_id,
        )
    )
    await db.execute(
        delete(AssessmentCriteriaPackage).where(
            AssessmentCriteriaPackage.assessment_id == assessment_id,
            AssessmentCriteriaPackage.control_id == control_id,
        )
    )


async def assess_control_with_assessor_pipeline(
    assessment_id: int,
    project_id: int,
    control,
    system_context: str,
    llm,
    db: AsyncSession,
    evidence_index: dict[str, list[dict[str, Any]]],
    skip_stage3: bool = False,
    policy_runtime: dict[str, Any] | None = None,
) -> LLMFinding | None:
    objectives = _dedupe_objectives(list(control.assessment_objectives or []))
    if not objectives:
        objectives = _dedupe_objectives(_derive_objectives_from_statement(control.display_id, control.statement or ""))
    if not objectives:
        return None

    await _reset_control_stage_rows(assessment_id, control.display_id, db)

    criteria_values = {
        "assessment_id": assessment_id,
        "control_id": control.display_id,
        "control_family": control.family_id.upper(),
        "control_title": control.title,
        "control_statement": control.statement or "",
        "supplemental_guidance": control.supplemental_guidance or None,
        "assessment_objectives": objectives,
        "criteria_metadata": {
            "catalog_id": control.id,
            "family_id": control.family_id,
            "family_title": control.family_title,
            "is_enhancement": control.is_enhancement,
            "parent_id": control.parent_id,
            "assessment_methods": control.assessment_methods,
            "organization_defined_parameters": control.organization_defined_parameters,
        },
    }
    await db.execute(
        insert(AssessmentCriteriaPackage)
        .values(criteria_values)
        .on_conflict_do_update(
            constraint="uq_assessment_criteria_control",
            set_={key: value for key, value in criteria_values.items() if key not in {"assessment_id", "control_id"}},
        )
    )

    candidate_packets = list(evidence_index.get(control.display_id, []))
    if not candidate_packets:
        candidate_packets = list(evidence_index.get("__all__", []))
    if not candidate_packets:
        return None
    objective_evidence_maps = _build_objective_evidence_maps(control, objectives, candidate_packets)
    union_considered_packets = _merge_unique_packets(
        [objective_map.get("considered_packets") or [] for objective_map in objective_evidence_maps.values()]
    )
    if not union_considered_packets:
        return None
    corroboration = _build_corroboration_summary(union_considered_packets)

    packet_objective_usage: dict[tuple[Any, Any], dict[str, Any]] = {}
    for objective_id, objective_map in objective_evidence_maps.items():
        for packet in objective_map.get("considered_packets") or []:
            identity = _packet_identity(packet)
            usage = packet_objective_usage.setdefault(
                identity,
                {
                    "packet": packet,
                    "objectives": [],
                    "roles": set(),
                    "max_score": 0.0,
                },
            )
            usage["objectives"].append(objective_id)
            usage["roles"].add(packet.get("triage_role") or "supporting")
            usage["max_score"] = max(usage["max_score"], float(packet.get("objective_relevance_score") or 0.0))

    triage_packets = sorted(
        packet_objective_usage.values(),
        key=lambda item: item["max_score"],
        reverse=True,
    )

    for idx, entry in enumerate(triage_packets):
        pkt = entry["packet"]
        role_text = ",".join(sorted(role for role in entry["roles"] if role))
        objective_text = ",".join(entry["objectives"][:12])
        db.add(
            AssessmentEvidenceTriage(
                assessment_id=assessment_id,
                control_id=control.display_id,
                unit_id=pkt.get("unit_id"),
                document_id=pkt.get("document_id"),
                source_type=pkt.get("source_type"),
                artifact_type=pkt.get("artifact_type"),
                evidence_strength=pkt.get("evidence_strength"),
                evidence_language_type=pkt.get("evidence_language_type"),
                document_type=pkt.get("document_type"),
                document_intent=pkt.get("document_intent"),
                triage_role=pkt.get("triage_role") or "supporting",
                relevance_score=pkt.get("relevance_score") or 0.0,
                citation_label=pkt.get("filename"),
                rationale=(
                    f"{pkt.get('classification_explanation') or ''} "
                    f"[objectives={objective_text}; roles={role_text}; max_objective_score={entry['max_score']:.2f}]"
                ).strip() or None,
                sort_order=idx,
            )
        )

    for objective_id, objective_map in objective_evidence_maps.items():
        prompt_identities = {
            _packet_identity(packet) for packet in (objective_map.get("prompt_packets") or [])
        }
        considered_packets = objective_map.get("considered_packets") or []
        sorted_packets = sorted(
            considered_packets,
            key=lambda item: float(item.get("objective_relevance_score") or 0.0),
            reverse=True,
        )
        for sort_order, packet in enumerate(sorted_packets):
            review_role = {
                "supporting": "supporting",
                "contradictory": "contradictory",
                "partial": "partial",
                "irrelevant": "context",
            }.get(packet.get("triage_role"), "context")
            db.add(
                ObjectiveEvidenceReview(
                    assessment_id=assessment_id,
                    control_id=control.display_id,
                    objective_id=objective_id,
                    objective_text=objective_map.get("objective_text"),
                    unit_id=packet.get("unit_id"),
                    document_id=packet.get("document_id"),
                    source_type=packet.get("source_type"),
                    artifact_type=packet.get("artifact_type"),
                    evidence_strength=packet.get("evidence_strength"),
                    document_type=packet.get("document_type"),
                    document_intent=packet.get("document_intent"),
                    review_role=review_role,
                    used_in_prompt=_packet_identity(packet) in prompt_identities,
                    packet_id=packet.get("packet_id"),
                    objective_relevance_score=float(packet.get("objective_relevance_score") or 0.0),
                    keyword_hits=list(packet.get("objective_keyword_hits") or []),
                    excerpt=packet.get("llm_excerpt") or None,
                    rationale=packet.get("classification_explanation") or None,
                    sort_order=sort_order,
                )
            )
    await db.commit()

    gap_analysis = await _run_objective_totality_review(
        control_id=control.display_id,
        control_title=control.title,
        objective_maps=objective_evidence_maps,
        system_context=system_context,
        llm=llm,
    )
    gap_analysis = _dedupe_gap_analysis(gap_analysis, objectives)
    if not gap_analysis:
        return None

    adjudication = _policy_based_verdict(
        assessment_id=assessment_id,
        control=control,
        objectives=objectives,
        gap_analysis=gap_analysis,
        objective_evidence_maps=objective_evidence_maps,
        corroboration=corroboration,
        policy_runtime=policy_runtime,
    )
    objective_rows = adjudication["objective_rows"]
    deduped_rows = {}
    for row in objective_rows:
        existing = deduped_rows.get(row["objective_id"])
        if existing is None:
            deduped_rows[row["objective_id"]] = row
            continue
        current_rank = {
            "met": 3,
            "partially_met": 2,
            "not_met": 1,
        }.get(row["status"], 0)
        existing_rank = {
            "met": 3,
            "partially_met": 2,
            "not_met": 1,
        }.get(existing["status"], 0)
        if current_rank > existing_rank or (current_rank == existing_rank and (row.get("supporting_citations") or []) and not (existing.get("supporting_citations") or [])):
            deduped_rows[row["objective_id"]] = row
    objective_rows = list(deduped_rows.values())
    gap_analysis = _effective_gap_analysis_from_objective_rows(gap_analysis, objective_rows)
    if objective_rows:
        objective_stmt = insert(ObjectiveDetermination).values(objective_rows)
        await db.execute(
            objective_stmt.on_conflict_do_update(
                constraint="uq_objective_determination",
                set_={
                    "objective_text": objective_stmt.excluded.objective_text,
                    "status": objective_stmt.excluded.status,
                    "rationale": objective_stmt.excluded.rationale,
                    "supporting_citations": objective_stmt.excluded.supporting_citations,
                    "contradictory_citations": objective_stmt.excluded.contradictory_citations,
                    "missing_evidence": objective_stmt.excluded.missing_evidence,
                    "confidence_score": objective_stmt.excluded.confidence_score,
                    "raw_llm_result": objective_stmt.excluded.raw_llm_result,
                    "adjudication_json": objective_stmt.excluded.adjudication_json,
                },
            )
        )
    await db.commit()

    status = adjudication["status"]
    confidence = adjudication["confidence"]
    shall_failures = adjudication["shall_failures"]
    gaps = _build_gaps_from_objective_rows(adjudication.get("objective_rows") or [], status)
    evidence_summary = adjudication["evidence_summary"]
    control_values = {
        "assessment_id": assessment_id,
        "control_id": control.display_id,
        "status": status,
        "confidence_score": confidence,
        "objective_summary": adjudication["objective_summary"],
        "deficiency_summary": "\n".join(gaps[:12]) if gaps else None,
        "evidence_summary": evidence_summary,
    }
    await db.execute(
        insert(ControlDetermination)
        .values(control_values)
        .on_conflict_do_update(
            constraint="uq_control_determination",
            set_={key: value for key, value in control_values.items() if key not in {"assessment_id", "control_id"}},
        )
    )
    await db.commit()

    challenge_note = await run_verdict_challenge(
        control_id=control.display_id,
        control_title=control.title,
        gap_analysis=gap_analysis,
        status=status,
        confidence=confidence,
        shall_failures=shall_failures,
        llm=llm,
    )
    challenge_values = {
        "assessment_id": assessment_id,
        "control_id": control.display_id,
        "concur": not bool(challenge_note),
        "dissent_note": challenge_note or None,
        "challenged_objectives": _extract_challenged_objectives(challenge_note),
        "model_name": getattr(llm, "model", None),
    }
    await db.execute(
        insert(AssessmentChallenge)
        .values(challenge_values)
        .on_conflict_do_update(
            constraint="uq_assessment_challenge",
            set_={key: value for key, value in challenge_values.items() if key not in {"assessment_id", "control_id"}},
        )
    )
    await db.commit()

    if skip_stage3:
        finding = _synthesize_narrative(
            status=status,
            confidence=confidence,
            gap_analysis=gap_analysis,
            control_id=control.display_id,
            control_title=control.title,
            objectives=objectives,
        )
    else:
        finding = await run_narrative(
            control_id=control.display_id,
            control_title=control.title,
            control_statement=control.statement,
            status=status,
            confidence=confidence,
            gap_analysis=gap_analysis,
            objectives=objectives,
            chunks=_merge_unique_packets(
                [objective_map.get("prompt_packets") or [] for objective_map in objective_evidence_maps.values()]
            ),
            system_context=system_context,
            llm=llm,
            shall_failures=shall_failures,
            challenge_note=challenge_note,
        )

    finding.llm_challenge_note = challenge_note or ""
    finding.needs_manual_review = adjudication["needs_manual_review"]
    finding.adjudication_summary = adjudication["objective_summary"]
    finding.status = status
    finding.confidence = confidence
    finding.gaps = gaps
    return finding
