"""Shared evidence-unit read helpers used in place of legacy chunk/tag tables."""
from __future__ import annotations

from collections import defaultdict
from datetime import datetime
from typing import Any

from sqlalchemy import func, or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.orm import (
    Document,
    EvidenceClassification,
    EvidenceUnit,
    IngestionRun,
    ParsedLine,
    ProjectCommonProvider,
)
from app.services.evidence_profiles import normalize_autogenerated_profile


def _source_type_for_doc(doc: Document, project_id: int) -> str:
    if doc.project_id == project_id:
        return "project"
    if doc.provider_id is not None:
        return "common_control"
    if doc.policy_library_id is not None:
        return "policy"
    if doc.procedure_library_id is not None:
        return "procedure"
    return "project"


def _matches_control(control_id: str, classification: EvidenceClassification | None) -> bool:
    if classification is None:
        return False
    control_ids = classification.control_ids or []
    enhancement_ids = classification.enhancement_ids or []
    if control_id in control_ids or control_id in enhancement_ids:
        return True
    return any(enh.startswith(f"{control_id}(") for enh in enhancement_ids)


def _latest_completed_runs_query(document_ids: list[int] | None = None):
    query = (
        select(
            IngestionRun.document_id.label("document_id"),
            func.max(IngestionRun.id).label("run_id"),
        )
        .where(IngestionRun.status == "complete")
        .group_by(IngestionRun.document_id)
    )
    if document_ids is not None:
        query = query.where(IngestionRun.document_id.in_(document_ids))
    return query.subquery()


async def build_scope_document_ids(project_id: int, db: AsyncSession) -> list[int]:
    indexed_statuses = ("complete", "indexed")

    linked_provider_ids = (
        await db.execute(
            select(ProjectCommonProvider.provider_id).where(ProjectCommonProvider.project_id == project_id)
        )
    ).scalars().all()

    scope_conditions = [
        Document.project_id == project_id,
        Document.policy_library_id.is_not(None),
        Document.procedure_library_id.is_not(None),
    ]
    if linked_provider_ids:
        scope_conditions.append(Document.provider_id.in_(linked_provider_ids))

    query = select(Document.id).where(
        Document.parse_status.in_(indexed_statuses),
        or_(*scope_conditions),
    )
    return list((await db.execute(query)).scalars().all())


async def get_document_evidence_payload(
    document_id: int,
    db: AsyncSession,
) -> dict[str, Any] | None:
    doc = await db.get(Document, document_id)
    if not doc:
        return None

    latest_runs = _latest_completed_runs_query([document_id])
    result = await db.execute(
        select(EvidenceUnit, EvidenceClassification)
        .join(latest_runs, latest_runs.c.run_id == EvidenceUnit.run_id)
        .outerjoin(EvidenceClassification, EvidenceClassification.unit_id == EvidenceUnit.id)
        .where(EvidenceUnit.document_id == document_id)
        .order_by(EvidenceUnit.id)
    )
    rows = result.all()

    chunks: list[dict[str, Any]] = []
    unique_controls: set[str] = set()
    total_tags = 0

    for idx, (unit, classification) in enumerate(rows):
        tags = []
        confidence = round(classification.model_confidence or 0.75, 3) if classification else 0.75
        notes = classification.explanation if classification else None
        for control_id in classification.control_ids or [] if classification else []:
            tags.append({
                "control_id": control_id,
                "confidence": confidence,
                "notes": notes,
            })
            unique_controls.add(control_id)
        for enhancement_id in classification.enhancement_ids or [] if classification else []:
            tags.append({
                "control_id": enhancement_id,
                "confidence": round(confidence * 0.9, 3),
                "notes": notes,
            })
            unique_controls.add(enhancement_id)

        total_tags += len(tags)
        chunks.append({
            "id": unit.id,
            "chunk_index": idx,
            "section_title": unit.section_path,
            "page_number": (unit.page_numbers or [None])[0],
            "token_count": unit.token_count,
            "content": unit.content,
            "tags": tags,
        })

    return {
        "document_id": doc.id,
        "filename": doc.filename,
        "parse_status": doc.parse_status,
        "parse_error": doc.parse_error,
        "total_chunks": len(chunks),
        "total_tags": total_tags,
        "unique_controls": len(unique_controls),
        "chunks": chunks,
    }


async def get_document_tag_summary(
    document_id: int,
    db: AsyncSession,
) -> dict[str, Any] | None:
    doc = await db.get(Document, document_id)
    if not doc:
        return None

    latest_runs = _latest_completed_runs_query([document_id])
    result = await db.execute(
        select(EvidenceClassification)
        .join(EvidenceUnit, EvidenceUnit.id == EvidenceClassification.unit_id)
        .join(latest_runs, latest_runs.c.run_id == EvidenceClassification.run_id)
        .where(EvidenceUnit.document_id == document_id)
    )

    tag_map: dict[str, dict[str, Any]] = {}
    for classification in result.scalars().all():
        confidence = classification.model_confidence or 0.75
        for control_id in list(classification.control_ids or []) + list(classification.enhancement_ids or []):
            entry = tag_map.setdefault(
                control_id,
                {"control_id": control_id, "max_confidence": 0.0, "citation_count": 0},
            )
            entry["max_confidence"] = max(entry["max_confidence"], confidence)
            entry["citation_count"] += 1

    tags = sorted(tag_map.values(), key=lambda item: item["max_confidence"], reverse=True)
    for entry in tags:
        entry["max_confidence"] = round(entry["max_confidence"], 2)

    return {
        "document_id": document_id,
        "parse_status": doc.parse_status,
        "total_controls_tagged": len(tags),
        "tags": tags,
    }


async def get_control_evidence_packets(
    control_id: str,
    project_id: int,
    db: AsyncSession,
    max_tokens: int = 8000,
    min_confidence: float = 0.45,
) -> list[dict[str, Any]]:
    scope_doc_ids = await build_scope_document_ids(project_id, db)
    if not scope_doc_ids:
        return []

    latest_runs = _latest_completed_runs_query(scope_doc_ids)
    result = await db.execute(
        select(EvidenceUnit, EvidenceClassification, Document)
        .join(latest_runs, latest_runs.c.run_id == EvidenceUnit.run_id)
        .join(Document, Document.id == EvidenceUnit.document_id)
        .outerjoin(EvidenceClassification, EvidenceClassification.unit_id == EvidenceUnit.id)
        .where(Document.id.in_(scope_doc_ids))
        .order_by(EvidenceUnit.id)
    )

    chunks: list[dict[str, Any]] = []
    total_tokens = 0
    for unit, classification, doc in result.all():
        if not _matches_control(control_id, classification):
            continue
        confidence = classification.model_confidence or 0.75 if classification else 0.0
        if confidence < min_confidence:
            continue
        tokens = len(unit.content or "") // 4
        if total_tokens + tokens > max_tokens:
            break
        profile = normalize_autogenerated_profile(
            doc,
            classification.artifact_type if classification else None,
            classification.evidence_strength if classification else None,
            classification.evidence_language_type if classification else None,
        )

        chunks.append({
            "content": unit.content,
            "filename": doc.filename or "Unknown",
            "document_type": doc.document_type or "other",
            "document_intent": doc.document_intent or "other",
            "date": doc.created_at.strftime("%Y-%m-%d") if doc.created_at else None,
            "confidence": confidence,
            "source_type": _source_type_for_doc(doc, project_id),
            "section_path": unit.section_path,
            "page_numbers": unit.page_numbers or [],
            "artifact_type": profile["artifact_type"],
        })
        total_tokens += tokens
    return chunks


async def build_system_context_from_evidence(
    project_id: int,
    db: AsyncSession,
    scope_doc_ids: list[int] | None = None,
    max_chars: int = 4000,
) -> str:
    doc_ids = scope_doc_ids or await build_scope_document_ids(project_id, db)
    if not doc_ids:
        return "No system context documents available."

    latest_runs = _latest_completed_runs_query(doc_ids)
    result = await db.execute(
        select(EvidenceUnit.content)
        .join(latest_runs, latest_runs.c.run_id == EvidenceUnit.run_id)
        .where(EvidenceUnit.document_id.in_(doc_ids))
        .order_by(EvidenceUnit.document_id, EvidenceUnit.id)
        .limit(20)
    )
    contents = [row[0] for row in result.fetchall() if row[0]]
    if contents:
        return "\n\n---\n\n".join(contents)[:max_chars]

    line_result = await db.execute(
        select(ParsedLine.content)
        .join(latest_runs, latest_runs.c.run_id == ParsedLine.run_id)
        .where(ParsedLine.document_id.in_(doc_ids))
        .order_by(ParsedLine.document_id, ParsedLine.line_number)
        .limit(60)
    )
    lines = [row[0] for row in line_result.fetchall() if row[0]]
    if lines:
        return "\n".join(lines)[:max_chars]

    return "No system context documents available."


async def get_all_evidence_text(
    project_id: int,
    db: AsyncSession,
    max_tokens: int,
    scope_doc_ids: list[int] | None = None,
) -> list[str]:
    doc_ids = scope_doc_ids or await build_scope_document_ids(project_id, db)
    if not doc_ids:
        return []

    latest_runs = _latest_completed_runs_query(doc_ids)
    result = await db.execute(
        select(EvidenceUnit.content, EvidenceUnit.token_count)
        .join(latest_runs, latest_runs.c.run_id == EvidenceUnit.run_id)
        .where(EvidenceUnit.document_id.in_(doc_ids))
        .order_by(EvidenceUnit.document_id, EvidenceUnit.id)
    )

    selected: list[str] = []
    total = 0
    for content, token_count in result.fetchall():
        tokens = token_count or len(content or "") // 4
        if total + tokens > max_tokens:
            break
        selected.append(content)
        total += tokens
    return selected


async def has_new_evidence_for_control_since(
    project_id: int,
    control_id: str,
    since: datetime,
    db: AsyncSession,
) -> bool:
    scope_doc_ids = await build_scope_document_ids(project_id, db)
    if not scope_doc_ids:
        return False

    latest_runs = _latest_completed_runs_query(scope_doc_ids)
    result = await db.execute(
        select(EvidenceClassification, Document.created_at)
        .join(EvidenceUnit, EvidenceUnit.id == EvidenceClassification.unit_id)
        .join(Document, Document.id == EvidenceUnit.document_id)
        .join(latest_runs, latest_runs.c.run_id == EvidenceClassification.run_id)
        .where(
            Document.id.in_(scope_doc_ids),
            Document.created_at > since,
        )
    )

    for classification, _created_at in result.all():
        if _matches_control(control_id, classification):
            return True
    return False


async def get_document_indexing_progress(
    document_ids: list[int],
    db: AsyncSession,
) -> dict[int, dict[str, int]]:
    if not document_ids:
        return {}

    latest_runs = (
        select(
            IngestionRun.document_id.label("document_id"),
            func.max(IngestionRun.id).label("run_id"),
        )
        .where(
            IngestionRun.document_id.in_(document_ids),
            IngestionRun.status.in_(("running", "complete")),
        )
        .group_by(IngestionRun.document_id)
        .subquery()
    )
    result = await db.execute(
        select(IngestionRun)
        .join(latest_runs, latest_runs.c.run_id == IngestionRun.id)
    )

    progress: dict[int, dict[str, int]] = {}
    for run in result.scalars().all():
        total_units = run.evidence_units_created or run.lines_screened or run.lines_parsed or 0
        tagged_units = run.units_classified or 0
        pct = round(tagged_units / total_units * 100) if total_units > 0 else 0
        progress[run.document_id] = {
            "total_chunks": total_units,
            "tagged_chunks": tagged_units,
            "pct": pct,
        }
    return progress
