"""Helpers for normalizing autogenerated evidence package classifications."""
from __future__ import annotations

from typing import Any

from app.models.orm import Document

_STRENGTH_RANK = {
    "insufficient": 0,
    "weak": 1,
    "moderate": 2,
    "strong": 3,
}


def _max_strength(current: str | None, minimum: str) -> str:
    current_value = (current or "").strip().lower()
    minimum_value = minimum.strip().lower()
    if _STRENGTH_RANK.get(current_value, -1) >= _STRENGTH_RANK[minimum_value]:
        return current_value
    return minimum_value


def normalize_autogenerated_profile(
    doc: Document,
    artifact_type: str | None,
    evidence_strength: str | None,
    evidence_language_type: str | None,
) -> dict[str, Any]:
    """Return the effective evidence profile for an autogenerated implements doc.

    The ingestion classifier can under-call synthetic/generated artifacts as
    ``other`` even when the document metadata already says they are technical
    implementation evidence. This helper preserves the package author's intent
    for autogenerated implementation packages while still leaving non-generated
    content untouched.
    """
    normalized = {
        "artifact_type": (artifact_type or "other"),
        "evidence_strength": (evidence_strength or "weak"),
        "evidence_language_type": (evidence_language_type or "mixed"),
    }
    if not (getattr(doc, "autogenerated", False) and getattr(doc, "document_intent", None) == "implements"):
        return normalized

    filename = (doc.filename or "").lower()
    document_type = (doc.document_type or "other").strip().lower()

    if document_type == "technical_artifact":
        normalized["artifact_type"] = "test_evidence" if "validation" in filename or "verification" in filename else "technical_config"
        normalized["evidence_strength"] = _max_strength(normalized["evidence_strength"], "strong")
        normalized["evidence_language_type"] = "objective_evidence"
    elif document_type == "ssp_narrative":
        normalized["artifact_type"] = "implementation_statement"
        normalized["evidence_strength"] = _max_strength(normalized["evidence_strength"], "moderate")
        normalized["evidence_language_type"] = "implementation_language"
    elif document_type == "procedure":
        normalized["artifact_type"] = "procedure"
        normalized["evidence_strength"] = _max_strength(normalized["evidence_strength"], "moderate")
        normalized["evidence_language_type"] = "procedural_language"
    elif document_type == "policy":
        normalized["artifact_type"] = "policy"
        normalized["evidence_strength"] = _max_strength(normalized["evidence_strength"], "moderate")
        normalized["evidence_language_type"] = "policy_language"

    return normalized
