"""Capture schema that legacy startup code created dynamically.

Revision ID: 7e9c6e129313
Revises: z8a9b0c1d2e3
Create Date: 2026-08-08
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "7e9c6e129313"
down_revision: Union[str, None] = "z8a9b0c1d2e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

DDL_STATEMENTS: tuple[str, ...] = (
    'ALTER TABLE documents ADD COLUMN IF NOT EXISTS artifact_controls JSONB',
    'ALTER TABLE control_closure_sessions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()',
    'ALTER TABLE documents ADD COLUMN IF NOT EXISTS document_type VARCHAR(64)',
    'ALTER TABLE documents ADD COLUMN IF NOT EXISTS document_intent VARCHAR(64)',
    'ALTER TABLE control_findings ADD COLUMN IF NOT EXISTS llm_challenge_note TEXT',
    "CREATE TABLE IF NOT EXISTS test_dataset_jobs (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    status VARCHAR(32) NOT NULL DEFAULT 'pending',\n                    progress_detail TEXT,\n                    error_message TEXT,\n                    content_json JSONB,\n                    generated_doc_ids JSONB,\n                    created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE INDEX IF NOT EXISTS ix_test_dataset_jobs_project_id ON test_dataset_jobs(project_id)',
    "CREATE TABLE IF NOT EXISTS assistant_conversations (\n                    id SERIAL PRIMARY KEY,\n                    mode VARCHAR(32) NOT NULL DEFAULT 'general',\n                    title VARCHAR(255),\n                    project_id INTEGER REFERENCES projects(id) ON DELETE CASCADE,\n                    assessment_id INTEGER REFERENCES assessments(id) ON DELETE CASCADE,\n                    created_by INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE INDEX IF NOT EXISTS ix_assistant_conversations_project_id ON assistant_conversations(project_id)',
    'CREATE INDEX IF NOT EXISTS ix_assistant_conversations_assessment_id ON assistant_conversations(assessment_id)',
    'CREATE TABLE IF NOT EXISTS assistant_context_attachments (\n                    id SERIAL PRIMARY KEY,\n                    conversation_id INTEGER NOT NULL REFERENCES assistant_conversations(id) ON DELETE CASCADE,\n                    attachment_type VARCHAR(32) NOT NULL,\n                    resource_id VARCHAR(128) NOT NULL,\n                    label VARCHAR(255),\n                    context_json JSONB,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )',
    'CREATE INDEX IF NOT EXISTS ix_assistant_context_attachments_conversation_id ON assistant_context_attachments(conversation_id)',
    'CREATE INDEX IF NOT EXISTS ix_assistant_context_attachments_type ON assistant_context_attachments(attachment_type)',
    'CREATE TABLE IF NOT EXISTS assistant_messages (\n                    id SERIAL PRIMARY KEY,\n                    conversation_id INTEGER NOT NULL REFERENCES assistant_conversations(id) ON DELETE CASCADE,\n                    role VARCHAR(16) NOT NULL,\n                    content TEXT NOT NULL,\n                    metadata_json JSONB,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )',
    'CREATE INDEX IF NOT EXISTS ix_assistant_messages_conversation_id ON assistant_messages(conversation_id)',
    'ALTER TABLE control_findings ADD COLUMN IF NOT EXISTS synthesized_narrative BOOLEAN DEFAULT FALSE',
    "CREATE TABLE IF NOT EXISTS artifact_validation_runs (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    source_mode VARCHAR(32) NOT NULL,\n                    source_run_id INTEGER NOT NULL,\n                    status VARCHAR(32) NOT NULL DEFAULT 'pending',\n                    summary_json JSONB,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE INDEX IF NOT EXISTS ix_artifact_validation_runs_project_id ON artifact_validation_runs(project_id)',
    "CREATE TABLE IF NOT EXISTS artifact_validation_results (\n                    id SERIAL PRIMARY KEY,\n                    validation_run_id INTEGER NOT NULL REFERENCES artifact_validation_runs(id) ON DELETE CASCADE,\n                    document_id INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,\n                    integrity_status VARCHAR(32) NOT NULL DEFAULT 'pending',\n                    ingestion_status VARCHAR(32) NOT NULL DEFAULT 'pending',\n                    retrieval_status VARCHAR(32) NOT NULL DEFAULT 'pending',\n                    control_mapping_status VARCHAR(32) NOT NULL DEFAULT 'pending',\n                    details_json JSONB,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE INDEX IF NOT EXISTS ix_artifact_validation_results_validation_run_id ON artifact_validation_results(validation_run_id)',
    "CREATE TABLE IF NOT EXISTS package_viability_runs (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    source_mode VARCHAR(32) NOT NULL,\n                    source_run_id INTEGER NOT NULL,\n                    expected_profile VARCHAR(64),\n                    viability_score DOUBLE PRECISION,\n                    status VARCHAR(32) NOT NULL DEFAULT 'pending',\n                    summary_json JSONB,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE INDEX IF NOT EXISTS ix_package_viability_runs_project_id ON package_viability_runs(project_id)',
    "CREATE TABLE IF NOT EXISTS system_knowledge_runs (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    source_mode VARCHAR(32) NOT NULL,\n                    source_run_id INTEGER NOT NULL,\n                    status VARCHAR(32) NOT NULL DEFAULT 'pending',\n                    summary_json JSONB,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    completed_at TIMESTAMP WITH TIME ZONE\n                )",
    'CREATE INDEX IF NOT EXISTS ix_system_knowledge_runs_project_id ON system_knowledge_runs(project_id)',
    "CREATE TABLE IF NOT EXISTS system_knowledge_assertions (\n                    id SERIAL PRIMARY KEY,\n                    run_id INTEGER NOT NULL REFERENCES system_knowledge_runs(id) ON DELETE CASCADE,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    category VARCHAR(64) NOT NULL,\n                    key VARCHAR(128) NOT NULL,\n                    value_json JSONB,\n                    normalized_value VARCHAR(255),\n                    confidence DOUBLE PRECISION,\n                    status VARCHAR(32) NOT NULL DEFAULT 'proposed',\n                    rationale TEXT,\n                    provenance_json JSONB,\n                    reviewed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,\n                    reviewed_at TIMESTAMP WITH TIME ZONE,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE INDEX IF NOT EXISTS ix_system_knowledge_assertions_project_id ON system_knowledge_assertions(project_id)',
    "CREATE TABLE IF NOT EXISTS tool_inventory (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    tool_name VARCHAR(255) NOT NULL,\n                    tool_category VARCHAR(64),\n                    vendor VARCHAR(128),\n                    deployment_scope VARCHAR(128),\n                    status VARCHAR(32) NOT NULL DEFAULT 'proposed',\n                    confidence DOUBLE PRECISION,\n                    provenance_json JSONB,\n                    reviewed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,\n                    reviewed_at TIMESTAMP WITH TIME ZONE,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE UNIQUE INDEX IF NOT EXISTS uq_tool_inventory_project_tool ON tool_inventory(project_id, tool_name)',
    "CREATE TABLE IF NOT EXISTS project_provider_responsibilities (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    provider_id INTEGER NOT NULL REFERENCES common_control_providers(id) ON DELETE CASCADE,\n                    scope_type VARCHAR(32) NOT NULL DEFAULT 'family',\n                    scope_id VARCHAR(64) NOT NULL,\n                    inheritance_type VARCHAR(32) NOT NULL DEFAULT 'shared',\n                    provider_coverage_status VARCHAR(32) NOT NULL DEFAULT 'partial',\n                    system_responsibility TEXT,\n                    rationale TEXT,\n                    provenance_json JSONB,\n                    status VARCHAR(32) NOT NULL DEFAULT 'proposed',\n                    reviewed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,\n                    reviewed_at TIMESTAMP WITH TIME ZONE,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE UNIQUE INDEX IF NOT EXISTS uq_project_provider_scope ON project_provider_responsibilities(project_id, provider_id, scope_type, scope_id)',
    'CREATE INDEX IF NOT EXISTS ix_project_provider_responsibilities_project_id ON project_provider_responsibilities(project_id)',
    "CREATE TABLE IF NOT EXISTS integration_accounts (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    connector_type VARCHAR(64) NOT NULL,\n                    name VARCHAR(255) NOT NULL,\n                    auth_mode VARCHAR(32) NOT NULL DEFAULT 'dry_run',\n                    status VARCHAR(32) NOT NULL DEFAULT 'configured',\n                    config_json JSONB,\n                    last_error TEXT,\n                    last_tested_at TIMESTAMP WITH TIME ZONE,\n                    last_run_at TIMESTAMP WITH TIME ZONE,\n                    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE INDEX IF NOT EXISTS ix_integration_accounts_project_id ON integration_accounts(project_id)',
    "CREATE TABLE IF NOT EXISTS integration_runs (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    account_id INTEGER NOT NULL REFERENCES integration_accounts(id) ON DELETE CASCADE,\n                    trigger_mode VARCHAR(32) NOT NULL DEFAULT 'manual',\n                    status VARCHAR(32) NOT NULL DEFAULT 'pending',\n                    records_seen INTEGER NOT NULL DEFAULT 0,\n                    assertions_created INTEGER NOT NULL DEFAULT 0,\n                    summary_json JSONB,\n                    error_message TEXT,\n                    started_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    completed_at TIMESTAMP WITH TIME ZONE\n                )",
    'CREATE INDEX IF NOT EXISTS ix_integration_runs_project_id ON integration_runs(project_id)',
    "CREATE TABLE IF NOT EXISTS telemetry_snapshots (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    account_id INTEGER NOT NULL REFERENCES integration_accounts(id) ON DELETE CASCADE,\n                    run_id INTEGER NOT NULL REFERENCES integration_runs(id) ON DELETE CASCADE,\n                    snapshot_type VARCHAR(64) NOT NULL,\n                    freshness_status VARCHAR(32) NOT NULL DEFAULT 'fresh',\n                    summary_json JSONB,\n                    collected_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE INDEX IF NOT EXISTS ix_telemetry_snapshots_project_id ON telemetry_snapshots(project_id)',
    "CREATE TABLE IF NOT EXISTS control_telemetry_posture (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    control_id VARCHAR(32) NOT NULL,\n                    source_kind VARCHAR(32) NOT NULL DEFAULT 'integration',\n                    source_ref VARCHAR(128) NOT NULL,\n                    support_status VARCHAR(32) NOT NULL DEFAULT 'unknown',\n                    freshness_status VARCHAR(32) NOT NULL DEFAULT 'fresh',\n                    confidence DOUBLE PRECISION,\n                    evidence_json JSONB,\n                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE UNIQUE INDEX IF NOT EXISTS uq_control_telemetry_posture ON control_telemetry_posture(project_id, control_id, source_kind, source_ref)',
    'CREATE INDEX IF NOT EXISTS ix_control_telemetry_posture_project_id ON control_telemetry_posture(project_id)',
    "CREATE TABLE IF NOT EXISTS drift_records (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    account_id INTEGER REFERENCES integration_accounts(id) ON DELETE CASCADE,\n                    run_id INTEGER REFERENCES integration_runs(id) ON DELETE CASCADE,\n                    source_kind VARCHAR(32) NOT NULL DEFAULT 'integration',\n                    scope_type VARCHAR(32) NOT NULL DEFAULT 'project',\n                    scope_id VARCHAR(128) NOT NULL,\n                    severity VARCHAR(16) NOT NULL DEFAULT 'low',\n                    status VARCHAR(16) NOT NULL DEFAULT 'active',\n                    title VARCHAR(255) NOT NULL,\n                    details_json JSONB,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE INDEX IF NOT EXISTS ix_drift_records_project_id ON drift_records(project_id)',
    'CREATE INDEX IF NOT EXISTS ix_drift_records_status ON drift_records(status)',
    "CREATE TABLE IF NOT EXISTS security_collectors (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    name VARCHAR(255) NOT NULL,\n                    collector_type VARCHAR(64) NOT NULL DEFAULT 'local_runtime',\n                    status VARCHAR(32) NOT NULL DEFAULT 'active',\n                    secret_encrypted BYTEA NOT NULL,\n                    metadata_json JSONB,\n                    last_seen_at TIMESTAMP WITH TIME ZONE,\n                    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE INDEX IF NOT EXISTS ix_security_collectors_project_id ON security_collectors(project_id)',
    'CREATE TABLE IF NOT EXISTS security_collector_nonces (\n                    id SERIAL PRIMARY KEY,\n                    collector_id INTEGER NOT NULL REFERENCES security_collectors(id) ON DELETE CASCADE,\n                    nonce VARCHAR(128) NOT NULL,\n                    seen_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )',
    'CREATE UNIQUE INDEX IF NOT EXISTS uq_security_collector_nonce ON security_collector_nonces(collector_id, nonce)',
    "CREATE TABLE IF NOT EXISTS security_assets (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    asset_type VARCHAR(64) NOT NULL,\n                    name VARCHAR(255) NOT NULL,\n                    external_id VARCHAR(255),\n                    criticality VARCHAR(32) NOT NULL DEFAULT 'medium',\n                    metadata_json JSONB,\n                    last_seen_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE UNIQUE INDEX IF NOT EXISTS uq_security_asset_name ON security_assets(project_id, asset_type, name)',
    'CREATE INDEX IF NOT EXISTS ix_security_assets_project_id ON security_assets(project_id)',
    "CREATE TABLE IF NOT EXISTS security_scans (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    collector_id INTEGER REFERENCES security_collectors(id) ON DELETE SET NULL,\n                    source VARCHAR(64) NOT NULL,\n                    scan_type VARCHAR(64) NOT NULL,\n                    status VARCHAR(32) NOT NULL DEFAULT 'pending',\n                    summary_json JSONB,\n                    started_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    completed_at TIMESTAMP WITH TIME ZONE\n                )",
    'CREATE INDEX IF NOT EXISTS ix_security_scans_project_id ON security_scans(project_id)',
    "CREATE TABLE IF NOT EXISTS security_findings (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    asset_id INTEGER REFERENCES security_assets(id) ON DELETE SET NULL,\n                    scan_id INTEGER REFERENCES security_scans(id) ON DELETE SET NULL,\n                    source VARCHAR(64) NOT NULL,\n                    category VARCHAR(64) NOT NULL,\n                    severity VARCHAR(16) NOT NULL DEFAULT 'medium',\n                    title VARCHAR(255) NOT NULL,\n                    status VARCHAR(32) NOT NULL DEFAULT 'open',\n                    fix_available BOOLEAN NOT NULL DEFAULT FALSE,\n                    cvss DOUBLE PRECISION,\n                    detected_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    resolved_at TIMESTAMP WITH TIME ZONE,\n                    metadata_json JSONB\n                )",
    'CREATE INDEX IF NOT EXISTS ix_security_findings_project_id ON security_findings(project_id)',
    'CREATE INDEX IF NOT EXISTS ix_security_findings_status ON security_findings(status)',
    "CREATE TABLE IF NOT EXISTS security_recommendations (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    key VARCHAR(128) NOT NULL,\n                    title VARCHAR(255) NOT NULL,\n                    domain VARCHAR(64) NOT NULL,\n                    severity VARCHAR(16) NOT NULL DEFAULT 'medium',\n                    score_impact INTEGER NOT NULL DEFAULT 0,\n                    status VARCHAR(32) NOT NULL DEFAULT 'open',\n                    summary TEXT,\n                    action TEXT,\n                    metadata_json JSONB,\n                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE UNIQUE INDEX IF NOT EXISTS uq_security_recommendation_key ON security_recommendations(project_id, key)',
    'CREATE INDEX IF NOT EXISTS ix_security_recommendations_project_id ON security_recommendations(project_id)',
    "CREATE TABLE IF NOT EXISTS security_build_snapshots (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    collector_id INTEGER REFERENCES security_collectors(id) ON DELETE SET NULL,\n                    label VARCHAR(128) NOT NULL,\n                    version VARCHAR(128),\n                    commit_ref VARCHAR(128),\n                    source VARCHAR(64) NOT NULL DEFAULT 'local_build',\n                    status VARCHAR(32) NOT NULL DEFAULT 'completed',\n                    build_date TIMESTAMP WITH TIME ZONE NOT NULL,\n                    security_score INTEGER,\n                    summary_json JSONB,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE INDEX IF NOT EXISTS ix_security_build_snapshots_project_id ON security_build_snapshots(project_id)',
    'CREATE INDEX IF NOT EXISTS ix_security_build_snapshots_build_date ON security_build_snapshots(build_date)',
    "CREATE TABLE IF NOT EXISTS security_runtime_snapshots (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    collector_id INTEGER REFERENCES security_collectors(id) ON DELETE SET NULL,\n                    source VARCHAR(64) NOT NULL DEFAULT 'collector',\n                    collected_at TIMESTAMP WITH TIME ZONE NOT NULL,\n                    security_score INTEGER,\n                    summary_json JSONB,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE INDEX IF NOT EXISTS ix_security_runtime_snapshots_project_id ON security_runtime_snapshots(project_id)',
    'CREATE INDEX IF NOT EXISTS ix_security_runtime_snapshots_collected_at ON security_runtime_snapshots(collected_at)',
    'CREATE TABLE IF NOT EXISTS security_tracked_settings (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    asset_id INTEGER NOT NULL REFERENCES security_assets(id) ON DELETE CASCADE,\n                    setting_key VARCHAR(128) NOT NULL,\n                    setting_label VARCHAR(255) NOT NULL,\n                    category VARCHAR(64) NOT NULL,\n                    current_value_json JSONB,\n                    current_value_hash VARCHAR(64) NOT NULL,\n                    first_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,\n                    last_seen_at TIMESTAMP WITH TIME ZONE NOT NULL,\n                    last_changed_at TIMESTAMP WITH TIME ZONE NOT NULL,\n                    source VARCHAR(64) NOT NULL\n                )',
    'CREATE UNIQUE INDEX IF NOT EXISTS uq_security_tracked_setting ON security_tracked_settings(project_id, asset_id, setting_key)',
    'CREATE INDEX IF NOT EXISTS ix_security_tracked_settings_project_id ON security_tracked_settings(project_id)',
    'CREATE TABLE IF NOT EXISTS security_setting_history (\n                    id SERIAL PRIMARY KEY,\n                    tracked_setting_id INTEGER NOT NULL REFERENCES security_tracked_settings(id) ON DELETE CASCADE,\n                    snapshot_type VARCHAR(32) NOT NULL,\n                    snapshot_id INTEGER NOT NULL,\n                    value_json JSONB,\n                    value_hash VARCHAR(64) NOT NULL,\n                    observed_at TIMESTAMP WITH TIME ZONE NOT NULL\n                )',
    'CREATE INDEX IF NOT EXISTS ix_security_setting_history_tracked_setting_id ON security_setting_history(tracked_setting_id)',
    "CREATE TABLE IF NOT EXISTS security_change_events (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    asset_id INTEGER REFERENCES security_assets(id) ON DELETE SET NULL,\n                    tracked_setting_id INTEGER REFERENCES security_tracked_settings(id) ON DELETE SET NULL,\n                    event_type VARCHAR(64) NOT NULL,\n                    category VARCHAR(64) NOT NULL,\n                    old_value_json JSONB,\n                    new_value_json JSONB,\n                    detected_at TIMESTAMP WITH TIME ZONE NOT NULL,\n                    source_snapshot_type VARCHAR(32) NOT NULL,\n                    source_snapshot_id INTEGER NOT NULL,\n                    impact_level VARCHAR(16) NOT NULL DEFAULT 'low',\n                    impact_direction VARCHAR(16) NOT NULL DEFAULT 'neutral',\n                    change_status VARCHAR(32) NOT NULL DEFAULT 'observed',\n                    summary VARCHAR(255) NOT NULL,\n                    details_json JSONB\n                )",
    'CREATE INDEX IF NOT EXISTS ix_security_change_events_project_id ON security_change_events(project_id)',
    'CREATE INDEX IF NOT EXISTS ix_security_change_events_detected_at ON security_change_events(detected_at)',
    'CREATE TABLE IF NOT EXISTS calibration_suites (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    name VARCHAR(255) NOT NULL,\n                    description TEXT,\n                    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )',
    'CREATE INDEX IF NOT EXISTS ix_calibration_suites_project_id ON calibration_suites(project_id)',
    'CREATE TABLE IF NOT EXISTS calibration_cases (\n                    id SERIAL PRIMARY KEY,\n                    suite_id INTEGER NOT NULL REFERENCES calibration_suites(id) ON DELETE CASCADE,\n                    control_id VARCHAR(32) NOT NULL,\n                    expected_status VARCHAR(32) NOT NULL,\n                    expected_objectives_json JSONB,\n                    expected_citations_json JSONB,\n                    notes TEXT,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )',
    'CREATE INDEX IF NOT EXISTS ix_calibration_cases_suite_id ON calibration_cases(suite_id)',
    "CREATE TABLE IF NOT EXISTS calibration_runs (\n                    id SERIAL PRIMARY KEY,\n                    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n                    source_type VARCHAR(32) NOT NULL,\n                    source_run_id INTEGER NOT NULL,\n                    status VARCHAR(32) NOT NULL DEFAULT 'pending',\n                    summary_json JSONB,\n                    runtime_snapshot_json JSONB,\n                    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    completed_at TIMESTAMP WITH TIME ZONE\n                )",
    'CREATE INDEX IF NOT EXISTS ix_calibration_runs_project_id ON calibration_runs(project_id)',
    'CREATE INDEX IF NOT EXISTS ix_calibration_runs_source ON calibration_runs(source_type, source_run_id)',
    'CREATE TABLE IF NOT EXISTS calibration_case_results (\n                    id SERIAL PRIMARY KEY,\n                    run_id INTEGER NOT NULL REFERENCES calibration_runs(id) ON DELETE CASCADE,\n                    control_id VARCHAR(32) NOT NULL,\n                    expected_status VARCHAR(32) NOT NULL,\n                    actual_status VARCHAR(32) NOT NULL,\n                    match_status VARCHAR(32) NOT NULL,\n                    delta_json JSONB,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )',
    'CREATE INDEX IF NOT EXISTS ix_calibration_case_results_run_id ON calibration_case_results(run_id)',
    'CREATE TABLE IF NOT EXISTS ingestion_config (\n                    id SERIAL PRIMARY KEY,\n                    key VARCHAR(128) UNIQUE NOT NULL,\n                    value_text TEXT,\n                    value_encrypted BYTEA,\n                    is_secret BOOLEAN NOT NULL DEFAULT FALSE,\n                    description TEXT,\n                    updated_by INTEGER REFERENCES users(id) ON DELETE SET NULL,\n                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )',
    'CREATE INDEX IF NOT EXISTS ix_ingestion_config_key ON ingestion_config(key)',
    'CREATE TABLE IF NOT EXISTS ingestion_config_audit (\n                    id SERIAL PRIMARY KEY,\n                    config_key VARCHAR(128) NOT NULL,\n                    old_value TEXT,\n                    new_value TEXT,\n                    changed_by INTEGER REFERENCES users(id) ON DELETE SET NULL,\n                    changed_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )',
    'CREATE INDEX IF NOT EXISTS ix_ingestion_config_audit_key ON ingestion_config_audit(config_key)',
    'CREATE TABLE IF NOT EXISTS control_corpus_versions (\n                    id SERIAL PRIMARY KEY,\n                    corpus_key VARCHAR(128) UNIQUE NOT NULL,\n                    display_name VARCHAR(255) NOT NULL,\n                    version VARCHAR(128) NOT NULL,\n                    description TEXT,\n                    corpus_json JSONB NOT NULL,\n                    is_active BOOLEAN NOT NULL DEFAULT FALSE,\n                    created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )',
    'CREATE INDEX IF NOT EXISTS ix_control_corpus_versions_active ON control_corpus_versions(is_active)',
    "CREATE TABLE IF NOT EXISTS ingestion_runs (\n                    id SERIAL PRIMARY KEY,\n                    document_id INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,\n                    config_snapshot JSONB,\n                    status VARCHAR(32) NOT NULL DEFAULT 'pending',\n                    current_stage VARCHAR(32),\n                    stage_parse VARCHAR(32) NOT NULL DEFAULT 'pending',\n                    stage_screen VARCHAR(32) NOT NULL DEFAULT 'pending',\n                    stage_expand VARCHAR(32) NOT NULL DEFAULT 'pending',\n                    stage_classify VARCHAR(32) NOT NULL DEFAULT 'pending',\n                    stage_embed VARCHAR(32) NOT NULL DEFAULT 'pending',\n                    lines_parsed INTEGER NOT NULL DEFAULT 0,\n                    lines_screened INTEGER NOT NULL DEFAULT 0,\n                    evidence_units_created INTEGER NOT NULL DEFAULT 0,\n                    units_classified INTEGER NOT NULL DEFAULT 0,\n                    units_embedded INTEGER NOT NULL DEFAULT 0,\n                    error_message TEXT,\n                    error_stage VARCHAR(32),\n                    started_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    completed_at TIMESTAMP WITH TIME ZONE,\n                    triggered_by INTEGER REFERENCES users(id) ON DELETE SET NULL\n                )",
    'CREATE INDEX IF NOT EXISTS ix_ingestion_runs_document_id ON ingestion_runs(document_id)',
    'CREATE INDEX IF NOT EXISTS ix_ingestion_runs_status ON ingestion_runs(status)',
    'ALTER TABLE ingestion_runs ADD COLUMN IF NOT EXISTS corpus_version VARCHAR(128)',
    'CREATE TABLE IF NOT EXISTS parsed_documents (\n                    id SERIAL PRIMARY KEY,\n                    run_id INTEGER NOT NULL REFERENCES ingestion_runs(id) ON DELETE CASCADE,\n                    document_id INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,\n                    parser_name VARCHAR(128),\n                    parser_version VARCHAR(128),\n                    parser_metadata JSONB,\n                    source_filename VARCHAR(512) NOT NULL,\n                    file_type VARCHAR(64) NOT NULL,\n                    page_count INTEGER,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )',
    'CREATE INDEX IF NOT EXISTS ix_parsed_documents_run_id ON parsed_documents(run_id)',
    "CREATE TABLE IF NOT EXISTS parsed_lines (\n                    id SERIAL PRIMARY KEY,\n                    run_id INTEGER NOT NULL REFERENCES ingestion_runs(id) ON DELETE CASCADE,\n                    document_id INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,\n                    line_number INTEGER NOT NULL,\n                    page_number INTEGER,\n                    section_path TEXT,\n                    table_id VARCHAR(128),\n                    row_index INTEGER,\n                    col_index INTEGER,\n                    cell_label VARCHAR(255),\n                    content_type VARCHAR(32) NOT NULL DEFAULT 'text',\n                    content TEXT NOT NULL\n                )",
    'CREATE INDEX IF NOT EXISTS ix_parsed_lines_run_id ON parsed_lines(run_id)',
    'CREATE INDEX IF NOT EXISTS ix_parsed_lines_document_id ON parsed_lines(document_id)',
    'ALTER TABLE parsed_lines ADD COLUMN IF NOT EXISTS block_id VARCHAR(128)',
    'ALTER TABLE parsed_lines ADD COLUMN IF NOT EXISTS block_type VARCHAR(64)',
    'CREATE TABLE IF NOT EXISTS screening_results (\n                    id SERIAL PRIMARY KEY,\n                    line_id INTEGER NOT NULL UNIQUE REFERENCES parsed_lines(id) ON DELETE CASCADE,\n                    run_id INTEGER NOT NULL REFERENCES ingestion_runs(id) ON DELETE CASCADE,\n                    relevance_score FLOAT NOT NULL DEFAULT 0.0,\n                    candidate_controls JSONB,\n                    candidate_enhancements JSONB,\n                    rationale TEXT,\n                    above_threshold BOOLEAN NOT NULL DEFAULT FALSE,\n                    screened_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )',
    'CREATE INDEX IF NOT EXISTS ix_screening_results_run_id ON screening_results(run_id)',
    'CREATE INDEX IF NOT EXISTS ix_screening_results_line_id ON screening_results(line_id)',
    'CREATE TABLE IF NOT EXISTS evidence_units (\n                    id SERIAL PRIMARY KEY,\n                    run_id INTEGER NOT NULL REFERENCES ingestion_runs(id) ON DELETE CASCADE,\n                    document_id INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,\n                    trigger_line_id INTEGER NOT NULL REFERENCES parsed_lines(id) ON DELETE CASCADE,\n                    source_line_ids JSONB NOT NULL,\n                    content TEXT NOT NULL,\n                    page_numbers JSONB,\n                    section_path TEXT,\n                    table_coordinates JSONB,\n                    token_count INTEGER NOT NULL DEFAULT 0,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )',
    'CREATE INDEX IF NOT EXISTS ix_evidence_units_run_id ON evidence_units(run_id)',
    'CREATE INDEX IF NOT EXISTS ix_evidence_units_document_id ON evidence_units(document_id)',
    'CREATE TABLE IF NOT EXISTS evidence_classifications (\n                    id SERIAL PRIMARY KEY,\n                    unit_id INTEGER NOT NULL UNIQUE REFERENCES evidence_units(id) ON DELETE CASCADE,\n                    run_id INTEGER NOT NULL REFERENCES ingestion_runs(id) ON DELETE CASCADE,\n                    control_ids JSONB,\n                    enhancement_ids JSONB,\n                    artifact_type VARCHAR(64),\n                    evidence_strength VARCHAR(32),\n                    evidence_language_type VARCHAR(64),\n                    explanation TEXT,\n                    model_name VARCHAR(128),\n                    model_confidence FLOAT,\n                    classified_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )',
    'CREATE INDEX IF NOT EXISTS ix_evidence_classifications_run_id ON evidence_classifications(run_id)',
    'CREATE TABLE IF NOT EXISTS evidence_embeddings (\n                    id SERIAL PRIMARY KEY,\n                    unit_id INTEGER NOT NULL UNIQUE REFERENCES evidence_units(id) ON DELETE CASCADE,\n                    run_id INTEGER NOT NULL REFERENCES ingestion_runs(id) ON DELETE CASCADE,\n                    model_name VARCHAR(128) NOT NULL,\n                    embedding vector(1024),\n                    embedded_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )',
    'CREATE INDEX IF NOT EXISTS ix_evidence_embeddings_run_id ON evidence_embeddings(run_id)',
    'ALTER TABLE document_chunks ALTER COLUMN section_title TYPE TEXT',
    'CREATE TABLE IF NOT EXISTS assessment_criteria_packages (\n                    id SERIAL PRIMARY KEY,\n                    assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE,\n                    control_id VARCHAR(32) NOT NULL,\n                    control_family VARCHAR(8) NOT NULL,\n                    control_title VARCHAR(512) NOT NULL,\n                    control_statement TEXT NOT NULL,\n                    supplemental_guidance TEXT,\n                    assessment_objectives JSONB,\n                    criteria_metadata JSONB,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    CONSTRAINT uq_assessment_criteria_control UNIQUE (assessment_id, control_id)\n                )',
    'CREATE INDEX IF NOT EXISTS ix_assessment_criteria_packages_assessment_id ON assessment_criteria_packages(assessment_id)',
    'CREATE INDEX IF NOT EXISTS ix_assessment_criteria_packages_control_id ON assessment_criteria_packages(control_id)',
    "CREATE TABLE IF NOT EXISTS assessment_evidence_triage (\n                    id SERIAL PRIMARY KEY,\n                    assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE,\n                    control_id VARCHAR(32) NOT NULL,\n                    unit_id INTEGER REFERENCES evidence_units(id) ON DELETE SET NULL,\n                    document_id INTEGER REFERENCES documents(id) ON DELETE SET NULL,\n                    source_type VARCHAR(32),\n                    artifact_type VARCHAR(64),\n                    evidence_strength VARCHAR(32),\n                    evidence_language_type VARCHAR(64),\n                    document_type VARCHAR(64),\n                    document_intent VARCHAR(64),\n                    triage_role VARCHAR(32) NOT NULL DEFAULT 'supporting',\n                    relevance_score FLOAT NOT NULL DEFAULT 0.0,\n                    citation_label VARCHAR(512),\n                    rationale TEXT,\n                    sort_order INTEGER NOT NULL DEFAULT 0,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()\n                )",
    'CREATE INDEX IF NOT EXISTS ix_assessment_evidence_triage_assessment_id ON assessment_evidence_triage(assessment_id)',
    'CREATE INDEX IF NOT EXISTS ix_assessment_evidence_triage_control_id ON assessment_evidence_triage(control_id)',
    'CREATE TABLE IF NOT EXISTS objective_determinations (\n                    id SERIAL PRIMARY KEY,\n                    assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE,\n                    control_id VARCHAR(32) NOT NULL,\n                    objective_id VARCHAR(128) NOT NULL,\n                    objective_text TEXT,\n                    status VARCHAR(32) NOT NULL,\n                    rationale TEXT,\n                    supporting_citations JSONB,\n                    contradictory_citations JSONB,\n                    missing_evidence TEXT,\n                    confidence_score FLOAT,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    CONSTRAINT uq_objective_determination UNIQUE (assessment_id, control_id, objective_id)\n                )',
    'CREATE INDEX IF NOT EXISTS ix_objective_determinations_assessment_id ON objective_determinations(assessment_id)',
    'CREATE INDEX IF NOT EXISTS ix_objective_determinations_control_id ON objective_determinations(control_id)',
    'CREATE TABLE IF NOT EXISTS control_determinations (\n                    id SERIAL PRIMARY KEY,\n                    assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE,\n                    control_id VARCHAR(32) NOT NULL,\n                    status VARCHAR(32) NOT NULL,\n                    confidence_score FLOAT,\n                    objective_summary JSONB,\n                    deficiency_summary TEXT,\n                    evidence_summary TEXT,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    CONSTRAINT uq_control_determination UNIQUE (assessment_id, control_id)\n                )',
    'CREATE INDEX IF NOT EXISTS ix_control_determinations_assessment_id ON control_determinations(assessment_id)',
    'CREATE INDEX IF NOT EXISTS ix_control_determinations_control_id ON control_determinations(control_id)',
    'CREATE TABLE IF NOT EXISTS assessment_challenges (\n                    id SERIAL PRIMARY KEY,\n                    assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE,\n                    control_id VARCHAR(32) NOT NULL,\n                    concur BOOLEAN NOT NULL DEFAULT TRUE,\n                    dissent_note TEXT,\n                    challenged_objectives JSONB,\n                    model_name VARCHAR(128),\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    CONSTRAINT uq_assessment_challenge UNIQUE (assessment_id, control_id)\n                )',
    'CREATE INDEX IF NOT EXISTS ix_assessment_challenges_assessment_id ON assessment_challenges(assessment_id)',
    'CREATE INDEX IF NOT EXISTS ix_assessment_challenges_control_id ON assessment_challenges(control_id)',
    "CREATE TABLE IF NOT EXISTS assessment_rollups (\n                    id SERIAL PRIMARY KEY,\n                    assessment_id INTEGER NOT NULL REFERENCES assessments(id) ON DELETE CASCADE,\n                    readiness VARCHAR(32) NOT NULL DEFAULT 'insufficient_evidence',\n                    summary_json JSONB,\n                    residual_risk_summary TEXT,\n                    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),\n                    CONSTRAINT uq_assessment_rollup UNIQUE (assessment_id)\n                )",
    'CREATE INDEX IF NOT EXISTS ix_assessment_rollups_assessment_id ON assessment_rollups(assessment_id)',

)


def upgrade() -> None:
    # Every statement is idempotent so this transition also supports databases
    # where the legacy application startup created some or all objects already.
    for statement in DDL_STATEMENTS:
        op.execute(sa.text(statement))


def downgrade() -> None:
    # This migration adopts pre-existing application data. Destructive downgrade
    # would risk deleting user evidence, findings, and audit records.
    pass
