"""add autogenerated tracking fields

Revision ID: r9m0n1o2p3q4
Revises: q8l9m0n1o2p3
Create Date: 2026-03-21

"""
from alembic import op
import sqlalchemy as sa

revision = 'r9m0n1o2p3q4'
down_revision = 'q8l9m0n1o2p3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Document: auto-generation tracking
    op.add_column('documents', sa.Column('autogenerated', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('documents', sa.Column('source_assessment_id', sa.Integer(), sa.ForeignKey('assessments.id', ondelete='SET NULL'), nullable=True))
    op.add_column('documents', sa.Column('source_remediation_report_id', sa.Integer(), sa.ForeignKey('remediation_reports.id', ondelete='SET NULL'), nullable=True))
    op.create_index('ix_documents_source_assessment_id', 'documents', ['source_assessment_id'])
    op.create_index('ix_documents_source_remediation_report_id', 'documents', ['source_remediation_report_id'])

    # RemediationReport: live progress + generated doc list
    op.add_column('remediation_reports', sa.Column('progress_detail', sa.Text(), nullable=True))
    op.add_column('remediation_reports', sa.Column('generated_doc_ids', sa.JSON(), nullable=True))


def downgrade() -> None:
    op.drop_index('ix_documents_source_remediation_report_id', 'documents')
    op.drop_index('ix_documents_source_assessment_id', 'documents')
    op.drop_column('documents', 'source_remediation_report_id')
    op.drop_column('documents', 'source_assessment_id')
    op.drop_column('documents', 'autogenerated')
    op.drop_column('remediation_reports', 'generated_doc_ids')
    op.drop_column('remediation_reports', 'progress_detail')
