"""Document upload and management API."""
import hashlib
import os
import uuid
from pathlib import Path

import aiofiles
from fastapi import APIRouter, Depends, File, HTTPException, UploadFile, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import get_settings
from app.core.database import get_db
from app.core.rbac import require_assessor, require_project_access, require_viewer
from sqlalchemy import func, distinct
from app.models.orm import Assessment, Document, Project
from app.models.schemas import DocumentResponse
from app.services.evidence_view import (
    get_document_evidence_payload,
    get_document_indexing_progress,
    get_document_tag_summary as get_evidence_tag_summary,
)

router = APIRouter(
    prefix="/projects/{project_id}/documents",
    tags=["documents"],
    dependencies=[Depends(require_project_access)],
)
settings = get_settings()

ALLOWED_EXTENSIONS = {
    ".pdf", ".docx", ".doc", ".xlsx", ".xls", ".pptx", ".ppt",
    ".vsdx", ".vsd", ".txt", ".md", ".png", ".jpg", ".jpeg",
    ".gif", ".tiff", ".bmp",
}

ALLOWED_MIME_TYPES = {
    "application/pdf",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/msword",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "application/vnd.visio",
    "application/vnd.ms-visio.drawing",
    "text/plain",
    "text/markdown",
    "image/png", "image/jpeg", "image/gif", "image/tiff", "image/bmp",
}


def _get_file_type(filename: str) -> str:
    return Path(filename).suffix.lower().lstrip(".")


@router.get("", response_model=list[DocumentResponse])
async def list_documents(
    project_id: int,
    db: AsyncSession = Depends(get_db),
    _: dict = Depends(require_viewer),
) -> list[DocumentResponse]:
    result = await db.execute(
        select(Document).where(Document.project_id == project_id).order_by(Document.created_at)
    )
    docs = result.scalars().all()

    # Build a map of assessment db_id → project_run_number for autogenerated docs
    assessment_ids = {d.source_assessment_id for d in docs if d.source_assessment_id}
    run_number_map: dict[int, int] = {}
    if assessment_ids:
        a_result = await db.execute(
            select(Assessment.id, Assessment.project_run_number)
            .where(Assessment.id.in_(assessment_ids))
        )
        run_number_map = {row[0]: row[1] for row in a_result.fetchall()}

    # Attach run number to each doc as a transient attribute for the response
    out = []
    for doc in docs:
        d = DocumentResponse.model_validate(doc)
        if doc.source_assessment_id and doc.source_assessment_id in run_number_map:
            d.source_assessment_run_number = run_number_map[doc.source_assessment_id]
        out.append(d)
    return out


@router.get("/processing-progress")
async def get_processing_progress(
    project_id: int,
    db: AsyncSession = Depends(get_db),
    _: dict = Depends(require_viewer),
):
    """Return ingestion pipeline stage progress for all documents currently in 'processing' state.
    Returns {doc_id: {stage, stage_parse, stage_screen, stage_expand, stage_classify, stage_embed,
                       lines_parsed, lines_screened, evidence_units, units_classified, units_embedded, pct}}"""
    from app.models.orm import IngestionRun
    from sqlalchemy import desc

    processing_result = await db.execute(
        select(Document.id).where(
            Document.project_id == project_id,
            Document.parse_status == "processing",
        )
    )
    processing_ids = [row[0] for row in processing_result.fetchall()]
    if not processing_ids:
        return {}

    # Get the latest active run for each processing document
    progress = {}
    for doc_id in processing_ids:
        run_result = await db.execute(
            select(IngestionRun)
            .where(IngestionRun.document_id == doc_id, IngestionRun.status == "running")
            .order_by(desc(IngestionRun.started_at))
            .limit(1)
        )
        run = run_result.scalar_one_or_none()
        if not run:
            progress[doc_id] = {"stage": "parse", "pct": 0}
            continue

        # Map stages to completion percentage (each stage = 20%)
        stage_order = ["parse", "screen", "expand", "classify", "embed"]
        completed = sum(
            1 for s in ["stage_parse", "stage_screen", "stage_expand", "stage_classify", "stage_embed"]
            if getattr(run, s) == "complete"
        )
        pct = completed * 20

        progress[doc_id] = {
            "stage":         run.current_stage or "parse",
            "stage_parse":   run.stage_parse,
            "stage_screen":  run.stage_screen,
            "stage_expand":  run.stage_expand,
            "stage_classify":run.stage_classify,
            "stage_embed":   run.stage_embed,
            "lines_parsed":  run.lines_parsed,
            "lines_screened":run.lines_screened,
            "evidence_units":run.evidence_units_created,
            "units_classified":run.units_classified,
            "units_embedded":run.units_embedded,
            "pct":           pct,
        }
    return progress


@router.get("/indexing-progress")
async def get_indexing_progress(
    project_id: int,
    db: AsyncSession = Depends(get_db),
    _: dict = Depends(require_viewer),
):
    """Return chunk-level tagging progress for all documents currently in 'indexing' state.
    Returns {doc_id: {total_chunks, tagged_chunks, pct}} — poll while any doc is indexing."""
    # Get all indexing docs for this project
    indexing_result = await db.execute(
        select(Document.id).where(
            Document.project_id == project_id,
            Document.parse_status == "indexing",
        )
    )
    indexing_ids = [row[0] for row in indexing_result.fetchall()]
    if not indexing_ids:
        return {}

    return await get_document_indexing_progress(indexing_ids, db)


@router.post("", response_model=DocumentResponse, status_code=status.HTTP_201_CREATED)
async def upload_document(
    project_id: int,
    file: UploadFile = File(...),
    db: AsyncSession = Depends(get_db),
    current_user: dict = Depends(require_assessor),
) -> DocumentResponse:
    # Verify project exists
    result = await db.execute(select(Project).where(Project.id == project_id))
    if not result.scalar_one_or_none():
        raise HTTPException(status_code=404, detail="Project not found")

    # Validate extension
    suffix = Path(file.filename).suffix.lower()
    if suffix not in ALLOWED_EXTENSIONS:
        raise HTTPException(status_code=400, detail=f"File type not allowed: {suffix}")

    # Read and validate size
    content = await file.read()
    max_bytes = settings.max_upload_size_mb * 1024 * 1024
    if len(content) > max_bytes:
        raise HTTPException(status_code=413, detail=f"File exceeds {settings.max_upload_size_mb}MB limit")

    # Compute hash (duplicate detection)
    file_hash = hashlib.sha256(content).hexdigest()
    existing = await db.execute(
        select(Document).where(Document.project_id == project_id, Document.file_hash == file_hash)
    )
    if existing.scalar_one_or_none():
        raise HTTPException(status_code=409, detail="This file has already been uploaded to this project")

    # Save to disk
    project_upload_dir = Path(settings.upload_dir) / str(project_id)
    project_upload_dir.mkdir(parents=True, exist_ok=True)
    unique_name = f"{uuid.uuid4().hex}{suffix}"
    file_path = project_upload_dir / unique_name
    async with aiofiles.open(file_path, "wb") as f:
        await f.write(content)

    doc = Document(
        project_id=project_id,
        filename=file.filename,
        file_path=str(file_path),
        file_type=_get_file_type(file.filename),
        file_hash=file_hash,
        file_size_bytes=len(content),
        parse_status="pending",
        uploaded_by=current_user["id"],
    )
    db.add(doc)
    await db.commit()
    await db.refresh(doc)

    return doc


@router.get("/download-all")
async def download_all_documents(
    project_id: int,
    db: AsyncSession = Depends(get_db),
    _: dict = Depends(require_viewer),
):
    """Download all documents for a project as a ZIP archive."""
    import io
    import zipfile
    from fastapi.responses import StreamingResponse

    result = await db.execute(
        select(Document).where(Document.project_id == project_id).order_by(Document.filename)
    )
    docs = result.scalars().all()

    if not docs:
        raise HTTPException(status_code=404, detail="No documents found for this project")

    buf = io.BytesIO()
    seen_names: dict[str, int] = {}
    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        for doc in docs:
            if not doc.file_path or not Path(doc.file_path).exists():
                continue
            # Deduplicate filenames inside the ZIP
            name = doc.filename or Path(doc.file_path).name
            if name in seen_names:
                seen_names[name] += 1
                stem = Path(name).stem
                suffix = Path(name).suffix
                name = f"{stem} ({seen_names[name]}){suffix}"
            else:
                seen_names[name] = 0
            zf.write(doc.file_path, arcname=name)

    buf.seek(0)
    return StreamingResponse(
        buf,
        media_type="application/zip",
        headers={"Content-Disposition": f"attachment; filename=project-{project_id}-documents.zip"},
    )


@router.get("/{document_id}/download")
async def download_document(
    project_id: int,
    document_id: int,
    db: AsyncSession = Depends(get_db),
    _: dict = Depends(require_viewer),
):
    """Download the original uploaded file."""
    from fastapi.responses import FileResponse as FR
    result = await db.execute(
        select(Document).where(Document.id == document_id, Document.project_id == project_id)
    )
    doc = result.scalar_one_or_none()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")
    if not Path(doc.file_path).exists():
        raise HTTPException(status_code=410, detail="File no longer exists on disk")
    return FR(
        path=doc.file_path,
        filename=doc.filename,
        media_type="application/octet-stream",
    )


@router.post("/{document_id}/reparse", response_model=DocumentResponse)
async def reparse_document(
    project_id: int,
    document_id: int,
    db: AsyncSession = Depends(get_db),
    _: dict = Depends(require_assessor),
) -> DocumentResponse:
    """Re-trigger parsing for a failed or stuck document."""
    result = await db.execute(
        select(Document).where(Document.id == document_id, Document.project_id == project_id)
    )
    doc = result.scalar_one_or_none()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")

    if not Path(doc.file_path).exists():
        raise HTTPException(status_code=409, detail="File no longer exists on disk — please re-upload")

    # Clear previous error and reset status
    doc.parse_status = "pending"
    doc.parse_error = None
    await db.commit()
    await db.refresh(doc)

    return doc


@router.post("/{document_id}/reindex", response_model=DocumentResponse)
async def reindex_document(
    project_id: int,
    document_id: int,
    db: AsyncSession = Depends(get_db),
    _: dict = Depends(require_assessor),
) -> DocumentResponse:
    """Re-trigger control tagging for a parsed document."""
    result = await db.execute(
        select(Document).where(Document.id == document_id, Document.project_id == project_id)
    )
    doc = result.scalar_one_or_none()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")

    if doc.parse_status in ("pending", "processing", "indexing", "queued"):
        raise HTTPException(status_code=409, detail="Document is already being processed or queued")

    if doc.parse_status not in ("complete", "indexed", "index_failed", "failed"):
        raise HTTPException(status_code=409, detail="Document must be fully parsed before indexing")

    doc.parse_status = "pending"
    doc.parse_error = None
    await db.commit()
    await db.refresh(doc)

    return doc


@router.get("/{document_id}/tags/summary")
async def get_document_tag_summary(
    project_id: int,
    document_id: int,
    db: AsyncSession = Depends(get_db),
    _: dict = Depends(require_viewer),
) -> dict:
    """Return count of control tags per control family for this document."""
    result = await db.execute(
        select(Document).where(Document.id == document_id, Document.project_id == project_id)
    )
    doc = result.scalar_one_or_none()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")
    payload = await get_evidence_tag_summary(document_id, db)
    return payload or {
        "document_id": document_id,
        "parse_status": doc.parse_status,
        "total_controls_tagged": 0,
        "tags": [],
    }


@router.post("/reindex-all")
async def reindex_all_documents(
    project_id: int,
    db: AsyncSession = Depends(get_db),
    _: dict = Depends(require_assessor),
) -> dict:
    """Queue control tagging for all parsed-but-not-indexed documents in the project."""
    result = await db.execute(
        select(Document).where(
            Document.project_id == project_id,
            Document.parse_status.in_(["complete", "indexed", "index_failed"]),
        )
    )
    docs = result.scalars().all()
    if not docs:
        return {"queued": 0, "message": "No documents eligible for indexing"}

    queued = 0
    for doc in docs:
        doc.parse_status = "pending"
        doc.parse_error = None
        queued += 1

    await db.commit()

    return {"queued": queued, "message": f"Queued {queued} document(s) for re-indexing"}


@router.get("/{document_id}/chunks")
async def get_document_chunks(
    project_id: int,
    document_id: int,
    db: AsyncSession = Depends(get_db),
    _: dict = Depends(require_viewer),
) -> dict:
    """Return evidence excerpts for a document with their control mappings."""

    result = await db.execute(
        select(Document).where(Document.id == document_id, Document.project_id == project_id)
    )
    doc = result.scalar_one_or_none()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")
    payload = await get_document_evidence_payload(document_id, db)
    return payload or {
        "document_id": doc.id,
        "filename": doc.filename,
        "parse_status": doc.parse_status,
        "parse_error": doc.parse_error,
        "total_chunks": 0,
        "total_tags": 0,
        "unique_controls": 0,
        "chunks": [],
    }


@router.delete("/{document_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_document(
    project_id: int,
    document_id: int,
    db: AsyncSession = Depends(get_db),
    _: dict = Depends(require_assessor),
) -> None:
    result = await db.execute(
        select(Document).where(Document.id == document_id, Document.project_id == project_id)
    )
    doc = result.scalar_one_or_none()
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")
    # Remove file from disk
    try:
        os.unlink(doc.file_path)
    except FileNotFoundError:
        pass
    await db.delete(doc)
    await db.commit()
